### ISSUE TITLE
kbox pull syntax

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox#1055]
I'm trying to write a bash script that automatically pulls the db and files down from pantheon live into kbox:

`kbox pull -- --database=live --newbackup=?? --files=live`

What do I need to put for `--newbackup` to get it to not make a new backup?  I tried `n`, `false`, and `0` but it still prompts me:

`Create a new DB backup? (y/N)`

Also, why do I need the `--` after `pull` before the optional arguments?  From the user's perspective, it would be easier without the `--`:

`kbox pull --database=live --newbackup=?? --files=live`

**Comment by pirog** [comment]
I think you want to use `--latest` instead of `--newbackup`. You can find all the options with `kbox pull -- --help`

The `--` is required because we need to differentiate kbox options from other kinds of options. Consider

`kbox drush status --verbose` 

Should that run `drush verbose` or should it run the kbox command verbose? What if i want to run both `drush status --verbose` and also `kbox verbose`? The `--` exists precisely to make things easier for the user.
