### ISSUE TITLE
Error pulling kalabox/pantheon-redis:latest (tag not found)

### ISSUE THREAD

**Issue by leevh** [kalabox/kalabox#1056]
Just updated to 0.11.3, tried to start app and got the following:

Pulling redis (kalabox/pantheon-redis:latest)...
ERROR: Tag latest not found in repository docker.io/kalabox/pantheon-redis
code1err:more:Pulling repository docker.io/kalabox/pantheon-redis

I'm looking to see if I can manually change the tag to v0.11.3, but thought you might need to know anyway :)  thanks!

**Comment by pirog** [comment]
@leevh is this on a new app or one that already existed?

**Comment by leevh** [comment]
already existed, also forgot to include the lines above that error:

WARNING: The KALABOX_PANTHEON_IMAGE_VERSION variable is not set. Defaulting to a blank string.
WARNING: The KALABOX_PANTHEON_IMAGE_VERSION variable is not set. Defaulting to a blank string.
Pulling redis (kalabox/pantheon-redis:latest)...
ERROR: Tag latest not found in repository docker.io/kalabox/pantheon-redis
code1err:more:Pulling repository docker.io/kalabox/pantheon-redis

**Comment by leevh** [comment]
Assuming I can just set 0.11.3 for that variable in installed.json?

**Comment by pirog** [comment]
yeah that makes sense. so we changed the logic that handles the pantheon version so that the version would be tied to the app version instead of the kalabox version but in retrospect we should have kept the older version there :/

So what i would do as a workaround here is to open up kalabox-compose.yml and kalabox-cli.yml and do a find replace on `KALABOX_PANTHEON_IMAGE_VERSION`... changing it to `v0.11.3`

Alternatively, and probably a safer bet, you can just push your changes to the app, destroy the app and then build a new one since that will have all the latest code.

**Comment by leevh** [comment]
workaround worked great, up and running again thanks @pirog !

**Comment by pirog** [comment]
Sure thing! sorry for the problem there!
