### ISSUE TITLE
DNS not being set?

### ISSUE THREAD

**Issue by joshkoenig** [kalabox/kalabox#111]
Possibly related to: https://github.com/kalabox/kalabox-app-examples/issues/3

I'm not able to get any apps running, and am noticing that the DNS step keeps wanting to run if I do multiple `kbox provisions`. Also, assuming that this writes to /etc/hosts, I'm not seeing anything there

```
joshk@steppinrazor kalabox (master)$ kbox provision
STEP [1] -- Checking if Boot2Docker is installed....
 --- Boot2Docker is installed.

STEP [2] -- Checking for KBOX Boot2Docker profile....
 --- Boot2Docker profile exists.

STEP [3] -- Checking for syncthing binary....
 --- Syncthing binary exists.

STEP [4] -- Checking for syncthing config....
 --- Syncthing config exists.

STEP [5] -- Checking if VirtualBox is running....
 --- VirtualBox: is currently running.

STEP [6] -- Checking firewall settings....
 --- Firewall settings: OK

STEP [7] -- Checking internet access....
 --- Internet access: OK

STEP [8] -- Checking disk free space....
 --- 127786 MB free of the required 1000 MB

STEP [9] -- Checking if DNS is set....
 --- DNS is not set.

STEP [10] -- Setting things up....
 ##### ADMINISTRATIVE PASSWORD WILL BE REQUIRED! #####
 --- Setting up DNS for Kalabox.
 ---

 --- Finished installing

STEP [11] -- Setting up and turning on the Kalabox VM....
info: B2D => Starting up...
Kalabox engine has been activated.
info: B2D => Started up.
 --- Waiting for VM and Docker daemon to start...
.o
Started.
Your environment variables are already set correctly.

STEP [12] -- Installing core services....
info: DOCKER => Pulling image. name=kalabox/debian:stable
info: DOCKER => Pulling image. name=kalabox/skydns:stable, name=kalabox_skydns, NetworkMode=bridge, 53/udp=[HostIp=172.17.42.1, HostPort=53],
info: DOCKER => Pulling image. name=kalabox/skydock:stable, name=kalabox_skydock, NetworkMode=bridge, Binds=[/var/run/docker.sock:/docker.sock],
info: DOCKER => Pulling image. name=kalabox/hipache:stable, name=kalabox_hipache, NetworkMode=bridge, 80/tcp=[HostIp=, HostPort=80], 8160/tcp=[HostIp=, HostPort=8160],
info: DOCKER => Pulling image. name=kalabox/dnsmasq:stable, name=kalabox_dnsmasq, , , NetworkMode=bridge, postProviderOpts=getDnsmasqPostProviderOpts,
 --- Core services installed.
STEP [13] -- Installing core sharing...
info: DOCKER => Pulling image. name=kalabox/syncthing:stable
 --- Core sharing installed.
STEP [14] -- Finishing up....
 - Installation complete!
```

**Comment by pirog** [comment]
We are writing to `/etc/resolver/kbox` ... that way we can write once during setup and reduce the pain of managing `/etc/hosts` especially since that requires repeated sudo access. 

Also def think this is related to kalabox/kalabox-app-examples#3

Would also paste (or email me) the more robust log that should be living in `~/.kalabox/logs. 

In the meantime my `/etc/resolver/kbox` file looks like

```
nameserver 10.13.37.42
nameserver 10.13.37.43
```

If you want to drop that in and run `kbox provision` again and then try an app install as well.

**Comment by joshkoenig** [comment]
Aha! I think I had some old cruft around. My `/etc/resolver/kbox` had the following:

```
nameserver 1.3.3.7
nameserver 10.13.37.42
nameserver 10.13.37.43
nameserver 10.13.37.42
nameserver 10.13.37.43
nameserver 10.13.37.42
nameserver 10.13.37.43
```

I deleted that file, re-ran provision. `/etc/resolver/kbox` now matches yours, but I'm still getting the same errors on install. I have already tried flushin the dns cache as per:

https://support.apple.com/en-us/HT202516

I reset the log file before re-running provision and trying an install again. A dump of the fresh `~/.kalabox/logs` file is here:

https://gist.github.com/joshkoenig/93a01b5a8bee6bce36cd

**Comment by pirog** [comment]
Nice... ok i already see the issue. YAY DEBUG LOGS.

I think you have a super early release of KB2 lingering which still has its IP set at 1.3.3.7 which we had to change since it is actually owned by someone else. 

I think you've got two viable options. There is an uninstaller script you can run in `./scripts/uninstall-darwin.sh` which should remove cruft from an old install. This is preferred and you might want to choose to not nuke VB. 

The second option is to either go into the VB interface and destroy KB2 or run `boot2docker --vm="Kalabox2" destroy` from YE OLD CLI.

**Comment by pirog** [comment]
If you run the script it should remove `/etc/resolver/kbox` as well so we can give that a go again too

**Comment by joshkoenig** [comment]
Ok I am nuking everything from orbit and re-installing. Will report back.

I'm also idling in #kalabox ;)

**Comment by pirog** [comment]
Great! 

Just jumped into #kalabox on the IRCs

**Comment by pirog** [comment]
Unless you think otherwise im going to close this in favor of
https://github.com/kalabox/kalabox-issues/issues/299
