### ISSUE TITLE
Create a step by step guide to signing our installers and then sign them

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox#1195]

**Comment by pirog** [comment]
We want to detail the steps that need to be taken to sign our apps on all the OS so that users do not get relevant security messages or need to change their security preferences 

- [ ] Detail steps on OSX
- [ ] Detail steps on Win
- [ ] Detail steps on Fedora
- [ ] Create new issue to implement this and put it in the backlog

**Comment by reynoldsalec** [comment]
Main challenges:

- Need to sign all of the DMG content
- Need to sign them on a Mac machine (there is a workaround of copying files over to a Mac machine via SSH, signing, and copying back the signed version to the machine making the build)

@rileysaurus will detail her findings further and close out this issue.

**Comment by rileysaurus** [comment]
Code signing must happen on a Mac and will not work on linux. In order to make this part of our CI process we will have to use SSH to run commands and RSYNC to transport built objects to the Mac.

All artifacts inside of DMG will need to be signed in addition to the DMG itself.

Import the two following Apple Intermediate Certificates into keychain on the Mac you will be code signing on.
[Developer ID Certification Authority] http://www.apple.com/certificateauthority/DeveloperIDCA.cer
[Apple Worldwide Developer Relations Certification Authority] http://www.apple.com/certificateauthority/AppleWWDRCAG2.cer

[Kalabox, Inc Certificate (will need to login to http://developer.apple.com using last pass credentials)]https://developer.apple.com/services-account/QH65B2/account/mac/certificate/downloadCertificateContent.action?content-type=text/x-url-arguments&accept=application/json&requestId=5d97940f-654f-45f4-y0ca-ccd4b92f61eb&userLocale=en_US&teamId=FY8GAUX282&certificateId=42Q82WCXEF&type=HXZEUKP0FP

Use the following command to codesign an artifact. See 'man codesign' on Mac for further details.
codesign -s <identity> -v <code-path>
