### ISSUE TITLE
Can't use Kalabox offline

### ISSUE THREAD

**Issue by jdleonard** [kalabox/kalabox#1227]
I ran into this when attempting to work on a flight without WiFi, but it is reproducible more generally:
1. Start a Kalabox app
2. Disable network connection
3. Visit Kalabox app's URL

Expected: Kalabox app's page displayed

Actual: "There is no Internet connection" (in Chrome)

I suspect that the non-local IP (10.13.37.100) being used is the cause. I'm running alpha2.

**Comment by reynoldsalec** [comment]
@jdleonard I think you're right, it's failing on the DNS.

Any trivial amount of internet will fix it, but we will need to address this going forward.

**Comment by pirog** [comment]
+1 we should look into this

**Comment by pirog** [comment]
I think this will be resolved by #1330

**Comment by richard-aronson** [comment]
Would love to see a fix for this. Offline use is very important to me. :-)

**Comment by pirog** [comment]
Good to know @richard-aronson. i know i personally would like this as well :)

**Comment by davidneedham** [comment]
Was this fixed? I'd love to be able to use Kalabox offline!

**Comment by pirog** [comment]
Fixed but haven't rolled out a new official release yet.

**Comment by davidneedham** [comment]
Should this have been included in Version 0.13.0-beta.2? I just updated and the local kalabox website doesn't seem to work when offline.

**Comment by pirog** [comment]
Hmmm, what are you getting? This works ok with me.

Many browsers dont let you do anything if you are offline. Not sure we can
do much about that. Our test for this is to turn off wifi and curl the site
in the terminal, which seems to work.

**Comment by davidneedham** [comment]
I was trying to access in the browser with no internet connection. I've definitely done this with other *AMP services. In fact, being able to work when traveling has always been one of the biggest benefits. Does this have to work a different way with Kalabox?

**Comment by pirog** [comment]
@davidneedham we don't use `/etc/hosts` to route DNS requests which i'm guessing is the biggest difference. 

I guess what i am saying is that the `kbox` sites are up and running whereas they were not when this issue was originally posted. 

I think what we need to do is figure out why most browsers are saying "no internet connection" even when our site is actually up and running. If we know why that happens we can probably provide, at the minimum, some documentation on how to handle this.

**Comment by sukottokun** [comment]
I just did a fresh kbox install and ran into this issue, which seem to be specific to [later versions](http://apple.stackexchange.com/questions/48499/using-dnsmasq-when-not-connected-to-the-internet) of OS X, I am on 10.11.6. If there is no solution I missed (fingers crossed), I will probably try the DNS settings described when I get to stable internet.

**Comment by pirog** [comment]
@sukottokun i'm not sure what we can do about this sadly, although open to suggestions. if you pull down a site and then switch the internet off and restart the site it is "up" insofar as you can curl the site and get the expected response, however the browser doesn't seem to care to even try since it sees that you are offline. 

I'm wondering if there is some sort of way to whitelist *.kbox domains or something like that

**Comment by davidneedham** [comment]
Have any idea how does MAMP or other XAMP services manage to work around
this?
ᐧ


David Needham
Enjoy Creativity

enjoycreativity.com | +1 (952) 222-7716 | Schedule a meeting
<https://www.enjoycreativity.com/meeting>

Sign up for our newsletter <http://eepurl.com/L9hW1>

**Comment by pirog** [comment]
If MAMP just uses `localhost` then it worked because its in `/etc/hosts`
and the browser might troll through that before looking for other things
for resolution.

Does MAMP use `localhost` or `*.local* OR WHAT?

**Comment by davidneedham** [comment]
Yeah, I think it does. The "pro" version of MAMP lets you specify your own
host or domain, but I haven't used it enough to know how it does it.
ᐧ


David Needham
Enjoy Creativity

enjoycreativity.com | +1 (952) 222-7716 | Schedule a meeting
<https://www.enjoycreativity.com/meeting>

Sign up for our newsletter <http://eepurl.com/L9hW1>

**Comment by pirog** [comment]
@davidneedham ... sorry, just to clarify. which one does it use? `localhost` or `*.local domains`?

**Comment by davidneedham** [comment]
It's been awhile since I used it, but I recall going to localhost/MAMP for
phpmyadmin and updating my hosts file by hand when I added new sites.  The
pro version lets you add custom hosts/domains (so you can also do *.local)
without editing the hosts file.
ᐧ


David Needham
Enjoy Creativity

enjoycreativity.com | +1 (952) 222-7716 | Schedule a meeting
<https://www.enjoycreativity.com/meeting>

Sign up for our newsletter <http://eepurl.com/L9hW1>

**Comment by pirog** [comment]
@davidneedham the host file way to do this makes sense (and it sadly not compat with how we do kalabox) but i'd be interested to hear how their `*.local` works since that presumably is closer to how our things work. good to know!

**Comment by jdleonard** [comment]
For anyone following/finding this thread who might not be aware, offline is working BEAUTIFULLY in Kalabox 2.1.2 following these instructions to tweak the hosts file: http://docs.kalabox.io/en/stable/troubleshooting/#working-offline
