### ISSUE TITLE
Provide sync command

### ISSUE THREAD

**Issue by gremy** [kalabox/kalabox#1248]
It would be nice to be able to run something like:
```kbox sync``` to force the syncing/re-syncing of the code, because it sometimes gets out of sync and the only solution is to run ```kbox restart``` (sometimes run that a couple times).

**Comment by pirog** [comment]
@gremy, i can certainly understand the rationale behind something like this. 

That said there are various annoying issues we still have with syncthing that might be causing this. 

Ideally, do you think it would be better for us to get syncthing to "just work" instead of providing another command which, based on your proposal, sounds a lot like a light wrapper around `kbox restart`?

**Comment by gremy** [comment]
I think that a light wrapper around ```kbox restart``` would be useful, and save alpha/beta users a lot of time and frustration until the syncing will be more stable.
Maybe ```kbox restart``` with an argument such as ```--code```.

**Comment by pirog** [comment]
@gremy my question was an either/or, not both, proposition. We can't dedicate time to a stop-gap that is more or less like an existing command unless we take time from something else ie getting syncing stable. 

Do you think your underlying syncing issue here is related to the other well documented syncthing issues? 
See: #1199 #1228

**Comment by pirog** [comment]
@gremy i think we are going to reevaluate how we handle syncthing in general. that would presumably cover your concern here so imma gonna close this for now.
