### ISSUE TITLE
Change location where kalabox apps are stored locally, like a second drive?

### ISSUE THREAD

**Issue by Soundvessel** [kalabox/kalabox#1266]
I just installed Kalabox v0.12.0-alpha.3 to a secondary SSD hard drive on my Windows 10 Pro desktop.

Pulling down an existing site from Pantheon I was surprised to find it put the code in a folder off from my personal Windows user folder of my main drive instead.

Is there a way to change the default folder Kalabox places apps? If not I feel it should be a decent feature request since many of us developers use extra drives to have the space for some of these larger apps.

**Comment by pirog** [comment]
So this is a bit tricky on our end. Here are a couple things to keep in mind

1. Because of the way `boot2docker/docker-machine` folder sharing works apps **MUST** be somewhere inside of `C:\Users`. Since most external drives are not mounted in `C:\Users` we are presented with a small problem between reliability and stability. 

2. In the meantime you certainly *could* mount a drive at `C:\Users\me\.kalabox\apps`. Maybe the current default location is not ideal but if we move it it still has to live somewhere in `C:\Users`.

3. If you create apps with the Kalabox CLI they will get created in your current working directory or wherever you specify with the `--dir` flag. Again they need to live inside of `C:\Users`

Based on the above do you have any suggestions on how we could achieve this? Maybe just documenting how to mount an external drive correctly?

**Comment by Soundvessel** [comment]
I think the solution, at least with Windows and Linux, is to create a hard folder symbolic link from where you wish to have your apps.

I will follow the command line steps for Windows 10 [here](http://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) and let you know how it pans out. Since it is done via command line I think this is something you may be able to automate allowing users to define a folder for the app location and that action using the command line actions to build the symbolic links. Just be sure to remove with your uninstaller ;)

**Comment by pirog** [comment]
I think the big question here is whether `docker-machine` is going to follow the symlink and share something like `C:\Users\kalabox -> X:\` 

Did you try something like this yet? Does it work?

**Comment by Soundvessel** [comment]
Symlinks, including hard junctions, did not work and produced error `code1err:more:` when I tried to add a new app (an existing Pantheon Drupal site).

Mounting a drive as the `/apps` folder produced the same `code1err:more:` error.

If the issue is with `boot2docker` perhaps we can make a feature request that could allow us to define where the `/apps` folder can go?

It is not going to be a good day for developers that run out of space on their main drive. This limitation means there is no recourse other than to delete things to make space or clone their primary drive to an upgrade.

**Comment by pirog** [comment]
Yeah that doesn't really surprise me. 

I think there are already a bunch of feature requests on the docker side of things to open up more sharing than just `C:\Users`. I would do some searches there. 

Obviously, we would love to support any mount directory but this is somewhat of a hard requirement for us right now.

**Comment by pirog** [comment]
Going to close this in favor of #1245
