### ISSUE TITLE
Cannot read property 'git_url' of undefined

### ISSUE THREAD

**Issue by magbicaleman** [kalabox/kalabox#1315]
Kalabox v 0.12.15
OS X El Capitan 10.11.4

This happened after I logged into Pantheon and pulled a site down. The code folder is empty, and remains empty even after I do a pull and seems that everything went well.

I Deleted the site and re-created it again through Kalabox gui, and same result; empty code folder, but no error. 

![screen shot 2016-05-04 at 8 38 01 am](https://cloud.githubusercontent.com/assets/735039/15014822/26a1db1e-11d6-11e6-8a03-8d849dea2d74.png)

**Comment by magbicaleman** [comment]
Closing issue same as https://github.com/kalabox/kalabox/issues/1262

**Comment by reynoldsalec** [comment]
@magbicaleman please download Kalabox Alpha4 (after uninstalling Alpha3) and let me know if this still occurs; I'm guessing you are experiencing the failure of validation that's detailed in #1262, but want to make sure.

On Alpha4, confirm that the sitename/environment variables are filled in on the Pantheon Add Site form:

![kalabox](https://cloud.githubusercontent.com/assets/1153738/15028047/afa993c8-11fb-11e6-97a7-f998e9f4c92f.png)

If validation doesn't get triggered on submitting blank values on that form, then we should reopen #1262.

If you or anyone else reading this issue is experiencing this problem in Alpha4 or later and can confirm that validation is working correctly on the form, see issue #1318

**Comment by rovo79** [comment]
I"m using alpha4, and receiving the error.
