### ISSUE TITLE
Previous Versions Downloads

### ISSUE THREAD

**Issue by Soundvessel** [kalabox/kalabox#1332]
I just posted a bug with Beta 1 that is a blocker. It would be nice to be able to find and download the last Alpha release so I have something working in the meantime. Could we add to the documentation where to access older releases?

**Comment by pirog** [comment]
@Soundvessel since our releases are all on github now. This should already be true.
https://github.com/kalabox/kalabox/releases

**Comment by pirog** [comment]
@reynoldsalec maybe we want a link on the download page for "Previous versions" and have that link to github?

**Comment by reynoldsalec** [comment]
@pirog I'd argue that we should have the previous versions on Github only. Since we can't support legacy Kalabox versions easily, the only cases in which someone should revert is if they are a power user like @Soundvessel and know what they're doing, or if we suggest reverting and provide linking in our communications (this should be a rare case).

**Comment by pirog** [comment]
@reynoldsalec i think we are getting our wirez mixed a bit here. 

I am suggesting we *ONLY* have *THE LINK* to previous github releases (just a single link to teh github releases page) on kalabox.io and not like a listing of all previous releases. 

Is that more or less what you mean?
