### ISSUE TITLE
imagick seems to have gone away in the most recent Pantheon beta

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1333]
Bug Report
==========

**Tell us about your setup**

What version of Kalabox are you using?

**v0.12.0-beta1**

What operating system are you using?

Ubuntu LTS (14.04/16.04)

Have you previously installed Kalabox? If so, what version?

No

**Tell us about your bug**

Give a brief description of what happened

It looks like there is a regression in the latest Pantheon beta re: imagick. Namely it doesn't seem to be there anymore.

Can you recreate this bug?

Yes

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Set up your drupal site so that it generates styles with imagick
2. Try to regenerate those styles with drush

**Comment by bradchesney79** [comment]
Been working on this all day-- I can get it into all the right places it seems. But, it won't make itself available to the php code that uses it.

Merely adding php5-imagick to the apt-get of the Dockerfile does install imagemagick (command line 'convert -version' works), the imagick.so is with all the other shared objects, and the imagick.ini file for loading the module with php seems to be there. However, no dice. PHP cannot make use of the library and phpinfo() shows glaring whitespace where the imagemagick extension should be.

**Comment by pirog** [comment]
@bradchesney79 these are all great notes. I'm planning to work on this on Thursday so if you want to hold off i'm pretty sure i can wrap it up then.

**Comment by bradchesney79** [comment]
So, I think Wand-config may not be available to the extension...

ln -s /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/MagickWand-config /usr/bin/
ln -s /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/Wand-config /usr/bin/


Need to reimage as I've solidly broken kbox rebuild as of recent.
Having trouble incorporating the command though. I keep SUPER FUBARing the Dockerfile.

**Comment by bradchesney79** [comment]
@pirog 
Sure, Thursday is good. I'm going to keep banging on it though...

**Comment by bradchesney79** [comment]
The juju that makes things work seems to be using kbox stop and killing the GUI before issuing the kbox rebuild--

System does not have docker installed via the normal package manager means-- sometimes is unavailable via CLI. Will file bug when I can nail down why/when better.

Complete reload:
 
/usr/bin/Wand-config
/usr/bin/MagickWand-config

both exist in that location.

-- I don't think the soft link did anything because the executables are not in the child directories of /usr/lib .
where one would hope. Imagick class still unavailable to PHP...

**Comment by bradchesney79** [comment]
Solved the docker command disappearing issue. If I open the terminal from the kalabox GUI, then docker commands like docker ps, docker exec, and docker commit always work.

If I just plain open a terminal like I have done for a decade or so, then docker is unavailable.

Still would like to find a better way to see if my interactive changes are taking. Meh.

**Comment by pirog** [comment]
so you shouldn't need to use `docker` straight up for any of this as `kbox rebuild` will handle that for you. If you do want to do that it is probably recommended to use go into the VM

```
~/.kalabox/bin/docker-machine ssh Kalabox2
cd /Users/path/to/dockerfile
docker build -t mytag .
```

**Comment by bradchesney79** [comment]
Who learned a lot about the platform? I did. I did. *hand waving furiously*

So, this is just the first working solution. I think I can do better.

@pirog you order a hot mess? Well, here's a working hot mess:

==========Pantheon App Server Dockerfile===============

# Pantheon appserver mock for Kalabox
# docker build -t kalabox/pantheon-appserver .
# docker run -d -e PHP_VERSION=55 -e FRAMEWORK=backdrop kalabox/pantheon-appserver

FROM nginx:1.8.1

# Set our customization options
ENV PHP_VERSION 53
ENV FRAMEWORK drupal
ENV DOMAIN kbox

# Update sources
# Same as before, but adds 'backports' repo
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak && \
  echo "deb http://httpredir.debian.org/debian jessie main" > /etc/apt/sources.list && \
  echo "deb http://httpredir.debian.org/debian jessie-updates main" >> /etc/apt/sources.list && \
  echo "deb http://httpredir.debian.org/debian jessie-backports main" >> /etc/apt/sources.list && \
  echo "deb http://security.debian.org jessie/updates main" >> /etc/apt/sources.list && \
  echo "deb http://nginx.org/packages/debian/ jessie nginx" >> /etc/apt/sources.list

# Install basic packages

RUN apt-get -y clean && apt-get -y update && apt-get -y install \
  curl bzip2 \
  libgmp10 libltdl7 libmcrypt4 libpq5 libicu52 libxslt1.1 && \
  apt-get -y clean && \
  apt-get -y autoclean && \
  apt-get -y autoremove && \
  rm -rf /var/lib/apt/* && rm -rf /var/lib/cache/* && rm -rf /var/lib/log/* && rm -rf /tmp/*

RUN apt-get -y clean && apt-get -y update && apt-get -y install \
  mysql-client postgresql-client-common sqlite && \
  apt-get -y clean && \
  apt-get -y autoclean && \
  apt-get -y autoremove && \
  rm -rf /var/lib/apt/* && rm -rf /var/lib/cache/* && rm -rf /var/lib/log/* && rm -rf /tmp/*

RUN apt-get -y clean && apt-get -y update && apt-get -y install \
  php5-cli php5-intl php5-curl php5-mysql php5-json && \
  apt-get -y clean && \
  apt-get -y autoclean && \
  apt-get -y autoremove && \
  rm -rf /var/lib/apt/* && rm -rf /var/lib/cache/* && rm -rf /var/lib/log/* && rm -rf /tmp/*

RUN apt-get -y clean && apt-get -y update && apt-get -y install \
  xfonts-base xfonts-75dpi && \
  apt-get -y clean && \
  apt-get -y autoclean && \
  apt-get -y autoremove && \
  rm -rf /var/lib/apt/* && rm -rf /var/lib/cache/* && rm -rf /var/lib/log/* && rm -rf /tmp/*

# wkhtmltopdf is crying about dependencies-- that dpkg -i should be taking care of
# possibly look at using gdebi...

RUN apt-get -y clean && apt-get -y update && apt-get -y install \
fontconfig libfontconfig1 libjpeg62-turbo libx11-6 libxext6 libxrender1 && \
  apt-get -y clean && \
  apt-get -y autoclean && \
  apt-get -y autoremove && \
  rm -rf /var/lib/apt/* && rm -rf /var/lib/cache/* && rm -rf /var/lib/log/* && rm -rf /tmp/*

# Get our phpbrew artifacts
RUN \
  mkdir -p /usr/local/bin && \
  curl -fsSL -o /usr/local/bin/phpbrew https://github.com/phpbrew/phpbrew/raw/master/phpbrew && \
  chmod +x /usr/local/bin/phpbrew && \
  phpbrew init && \
  cd /root/.phpbrew && \
  curl -L "http://github.com/kalabox/phpbrewer/releases/download/pantheon-beta1/php.tar.gz" | tar -zvx

# get some extra tools we need for pantheon
RUN \
  cd /tmp && curl -O 'http://download.gna.org/wkhtmltopdf/0.12/0.12.2/wkhtmltox-0.12.2_linux-jessie-amd64.deb'

RUN \
  cd /tmp && dpkg -i /tmp/wkhtmltox-0.12.2_linux-jessie-amd64.deb

RUN \
  mkdir -p /srv/bin && ln -s /usr/local/bin/wkhtmltopdf /srv/bin/wkhtmltopdf

RUN \
  cd /srv/bin && \
  curl -fsSL "https://github.com/bradchesney79/phantomjs-2.1.1-aws-failure-mirror/raw/master/phantomjs-2.1.1-linux-x86_64.tar.bz2" | tar -xjv && \
  mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /srv/bin/phantomjs && \
  rm -rf phantomjs-2.1.1-linux-x86_64 && rm -f phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
  chmod +x /srv/bin/phantomjs && \
  apt-get clean && \
  apt-get -y autoclean && \
  apt-get -y autoremove && \
  rm -rf /var/lib/apt/* && rm -rf /var/lib/cache/* && rm -rf /var/lib/log/* && rm -rf /tmp/*

# Get the tools for creating imagick.so
RUN apt-get -y clean && apt-get -y update && apt-get -y install \
  vim imagemagick php5-dev libmagickwand-dev pkg-config && \
  apt-get -y clean && \
  apt-get -y autoclean && \
  apt-get -y autoremove && \
  rm -rf /var/lib/apt/* && rm -rf /var/lib/cache/* && rm -rf /var/lib/log/* && rm -rf /tmp/*

RUN \
  export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/ && \
  mkdir -p /root/imagick && \
  cd /root/imagick && \
  curl -fsSL "http://pecl.php.net/get/imagick" | tar -xzv

RUN \
  cd /root/imagick/imagick-3.4.2/ && \
  phpize

RUN \
  cd /root/imagick/imagick-3.4.2/ && \
  ./configure --with-php-config=/root/.phpbrew/php/php-5.3.29/bin/php-config

RUN \
  cd /root/imagick/imagick-3.4.2/ && \
  make && \
  make install

#RUN \
#  ln -s /root/imagick/imagick-3.4.2/modules/imagick.so /root/.phpbrew/php/php-5.3.29/lib/php/extensions/#no-debug-non-zts-20090626/imagick.so && \

RUN \
  echo "extension=imagick.so" > /root/.phpbrew/php/php-5.3.29/var/db/imagick.ini

COPY ./start.sh /root/start.sh
COPY ./bashrc /root/.bashrc

# We do this because we need the stuff in .bashrc before we run start.sh
ENTRYPOINT ["/bin/bash"]
CMD ["--login", "/root/start.sh"]

EXPOSE 80
EXPOSE 443

**Comment by pirog** [comment]
@bradchesney79 have you looked at the https://github.com/kalabox/phpbrewer project? I think this is where we want to do all relevant config for the pantheon appserver. It's a shame docker doesnt have a 5.3 image to use instead.

**Comment by bradchesney79** [comment]
So, I switched to my main machine to try and port over the insights to the phpbrewer thing. The phpbrewer project is independent of the kalabox repo/app for the most part, should be okay on my lappy. --All these shenanigans is because configuration settings have breaking changes between PHP 5.3 and the Imagick 3.x versions. The actual code works fine once all the things are chained together correctly. Debian Jessie >> nginx >> PHP 5.3 (phpbrewer) >> Imagick 3.x (built) >> MagickWand 6 (generated from dev packages & imagick build) >> ImageMagick 9 (package).

However, Docker is not cooperating with Kubuntu for development... Yaargh!

**Comment by bradchesney79** [comment]
Docker cooperating... wouldn't mind a quick call (20 mins) to make sure what I'm doing in phpbrewer is the  envisioned improvement-- fairly certain I can make it work. It is 3:15PM DST (1915 UTC). I should be free in two hours (2115 UTC). It was like magic seeing everything imagick happen yesterday.



sudo apt-get autoremove --purge docker-engine && sudo apt-get autoremove --purge docker
curl -sSL https://get.docker.com/ | sh

...if anyone was wondering for *buntu 15.10

**Comment by pirog** [comment]
Does `phpbrew ext install imagick` not work?

**Comment by bradchesney79** [comment]
I can get the docker image to build, but the container doesn't seem to be working the way I think it should.
Total PEBCAK issue if you ask me...

**Comment by pirog** [comment]
You need to build the php binary and config with phpbrewer and then use those build artifacts in the actual appserver image.

**Comment by pirog** [comment]
So having talked to @reynoldsalec about this i think it might be best to move away from the current php appserver image and use two, one for 5.3 and one for 5.5. The original reasons we were using phpbrewer are not really relevant anymore.

**Comment by bradchesney79** [comment]
Oh. Very well then. How can I help?

**Comment by pirog** [comment]
I've got a working branch over here 
https://github.com/kalabox/kalabox-app-pantheon/tree/1333-imagick

The big thing to start with is to just get nginx/php to place nice with each other. Once we have that it will be easy to start adding in additional features like imagick via the traditional docker mechanisms.
