### ISSUE TITLE
Error querying docker for list of containers.: operation timed out

### ISSUE THREAD

**Issue by jpilcher** [kalabox/kalabox#1387]
Bug Report
==========

v0.12.0-beta.1 Windows 10 Pro

I've never installed Kalabox before.

Every time I try to create a site either from an existing Pantheon site or a new install I get this error after about 30 seconds.

`Error querying docker for list of containers.: operation timed out`

I've reinstalled twice and updated virtual box to 5.0.20.

Does this bug prevent you from using Kalabox?
Yes

**Comment by pirog** [comment]
Going to close in favor of https://github.com/kalabox/kalabox/issues/1387

**Comment by pirog** [comment]
So this happens when the docker daemon crashes (likely only happens on win/osx). You can replicate by going into the VM, turning docker off and then trying to run a kbox command that requires the daemon. This likely also produces the "cannot connect to the docker daemon" error. 

The relevant command to run is `docker-machine ssh Kalabox2 /etc/init.d/docker restart`. A fallback could be restarting the whole VM via `kbox down` and `kbox up`.
