### ISSUE TITLE
[Pantheon] Allow pulling database from ALL MultiDevs

### ISSUE THREAD

**Issue by RobLoach** [kalabox/kalabox#1425]
The database can only pull certain MultiDevs. It would be great to be able to pull the DB from all available MultiDevs.
![screenshot at 2016-06-29 15 36 30](https://cloud.githubusercontent.com/assets/25086/16465997/75469074-3e0f-11e6-817a-69caaac9cd1d.png)

**Comment by gremy** [comment]
+1

**Comment by pirog** [comment]
Unless there is overwhelming desire for this feature i think one of two workflows makes more sense

1. **Creating one Kalabox app per multidev environment** - You would do this when you NEED the database for development and its integrity is important.

2. **Pulling down dev and switching branches manually with git** - You would do this when the database state is not essential and just having the code is sufficient. 

Regardless we should document these two approaches in our pantheon docs.

**Comment by pirog** [comment]
I dont think we plan to support this option but we have documented a few workflows for it over at http://pantheon.kalabox.io (we are launching these docs now so they might not show up for a bit)

**Comment by RobLoach** [comment]
With the latest KalaBox, it looks like it's possible to pull from any environment. Could be wrong, but this looks good here. :+1:

**Comment by pirog** [comment]
i dont think this is true?

**Comment by RobLoach** [comment]
Ah, during creation, you can pull from a whole bunch of different environments...
![env](https://cloud.githubusercontent.com/assets/25086/17304893/ddb49caa-57f5-11e6-9b10-d6fa3af66ad9.png)


Can't do that during `kbox pull`.

**Comment by pirog** [comment]
@RobLoach this is all by design. You can read more about it in our docs
http://pantheon.kalabox.io/en/stable/users/best/#working-with-pantheon-multidev

**Comment by RobLoach** [comment]
Engage.

**Comment by dalin-** [comment]
@pirog 
Can you give more info about why Kalabox shouldn't support pulling a DB from any multi-dev?  It just seems like a waste to have multiple codebases/DBs/time-spent-creating-them when I only work on one branch at a time.

**Comment by dalin-** [comment]
As a hack, I was able to do this by editing `kalabox.yml` and changing `pluginconfig.pantheon.env` and `pluginconfig.pantheon.upstream.branch`.  

Seems to work just fine.

**Comment by pirog** [comment]
@dalin- we sort of explain this in the docs but the tl;dr is that its the easiest and most reliable way to work on multidev esp when you consider the breadth of skill of our user base. 

Generally if you know what you are doing you should have all your relevant config in code anyway and then working on multidev is really just switching branches. 

The situation we want to avoid is people getting their DB/Branch decoupled because over time that is going to probably get confusing/untrackable/result in the wrong things getting pushed to the wrong places. This is esp true if you dont really know how things work behind the scenes. 

If you are using something like `stage_file_proxy` then the only real difference from what you are proposing and what we are doing is the time it takes to clone another git repository which in a BEST PRACTICES scenario is probably 200MB max which on a NORMAL internet connection is only about a 5 minute download. This seems pretty reasonable to me.
