### ISSUE TITLE
How to use kbox terminus site set-php-version?

### ISSUE THREAD

**Issue by ptmkenny** [kalabox/kalabox#1444]
I'm trying to use `kbox terminus site set-php-version` to set the version of PHP that kbox uses for my site.  I need to change the PHP version for testing purposes.

At first, the command failed because somehow the machine token with Pantheon had gotten lost. After re-generating a new token and entering it via the command line, I was able to use `kbox terminus site set-php-version` to set the PHP version on Pantheon.

However, I don't see how I can change the PHP version of kbox.

I tried `kbox terminus sites list` but the kbox site is not listed.

**Comment by pirog** [comment]
@ptmkenny to be clear here: `terminus` is a tool JUST to interact with Pantheon. It does not have any control over your local Kalabox site so what you are describing is indeed the expected behavior. 

If you are interested in changing php versions check out our documentation 
http://pantheon.kalabox.io/en/stable/users/config/

As noted over in https://github.com/kalabox/kalabox/issues/1438 we only support easy version changing between 5.3 and 5.5 right now. If you want a different php version right now you'd have to use your own custom dockerfile.
