### ISSUE TITLE
How to update to a new version of Kalabox?

### ISSUE THREAD

**Issue by yumyo** [kalabox/kalabox#1447]
What is the official way to update Kalabox? Reading through other issues, it seems that the suggested way to update is uninstalling first. But uninstalling also destroy local apps. Which is most efficient way to to backup them first?

**Comment by pirog** [comment]
@yumyo i personally consider pantheon as my backup. so i just do the full uninstall and then pull the sites again. 

Generally the uninstall/reinstall is only required for a minor version bump ie from 0.12.x to 0.13.x. We try to do the best we can to allow for seamless upgrades between bumps between say 0.13.1 and 0.13.2 which means you should be able to just download the new version and run the installer.

We've got some of that info over at http://docs.kalabox.io/en/stable/users/install/
but perhaps it would be good for an upgrade doc as well?

**Comment by yumyo** [comment]
thanks @pirog using pantheon dev as backup make sense, at least 'til waiting for seamless upgrades.

**Comment by pirog** [comment]
Awesome! I think we should get to seamless upgrades in a few releases as we start to lock down all the core features.

How do you feel about having an upgrade section in the docs based on what i said in the comment above?

**Comment by jsibley2** [comment]
What is the best way to know that a new version is available, particularly when kalabox has been uninstalled? And is it available at kalabox.io when it is available on git, or at some point after that? Thanks.

**Comment by pirog** [comment]
This issue is about updating/upgrading to a new Kalabox version. So let's try to stay on topic.

That said, official/stable releases are available on both `kalabox.io` and github. We are posting alpha releases of the new 0.13.x branch which is *TRY AT YOUR OWN RISK* right now on github as well. 

Development releases which are, as you might image, risky to use are also posted and you can read about those in the readme for this project. 

Signing up for the newsletter on kalabox.io is probably your best bet for updates.
