### ISSUE TITLE
Write GUI protractor tests for Machine Token auth

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1456]

**Comment by reynoldsalec** [comment]
I'm wondering if something is incorrect with the permissions for accessing the nwjs binary in the .nwjs-builder/caches directory; if I copy one of the binaries that I know works when I run it form dist/gui/kalabox-ui/Kalabox.app into the .nwjs-builder/caches directory, it doesn't work. Maybe we can look at that tomorrow @pirog, since my preferred solution to this problem would be to reference assets from that .nwjs-builder directory, rather than maintaining our own logic for downloading the chromedriver/nwjs binary...I'm so sure this should be working and that I'm missing something small.

Alternatively, we could just use the binary in dist/gui, and reference the chromedriver that's downloaded by nwjs-builder (since that seems to work), but we'd have to see if we can access the binary on Linux in that case.

**Comment by pirog** [comment]
Hmmm, i feel like if the `nw-builder` task launches the GUI then the permissions on the NWJS binary are probably be ok. I think as long as you are at least `755` and executable it should be fine. 

Definitely down to get another set of eyes on this.

**Comment by pirog** [comment]
@reynoldsalec had to make a couple tweaks to get this to work on OSX for me (namely auto selenium setup). See commits above. 

Immediately fails with non-descript error on Linux. Going to wait to review this with you before i move on.

**Comment by pirog** [comment]
@reynoldsalec ok so i just needed to make sure java was installed and change the binaries around on Linux and Windows. So here are the things we need to do still

- [ ] @pirog verify that windows works as well
- [ ] @pirog verify java is on travis
- [ ] @reynoldsalec add in machine token protractor test
- [ ] @pirog update the mail testing docs

**Comment by pirog** [comment]
@reynoldsalec windows shows up as ia32 in my VM so i made some changes (https://github.com/kalabox/kalabox/commit/b4766a2ff0ba6ad822a3c09864b6755c15aa83b8) to our protractor conf to handle both different platforms and architectures. So, unless i broke something doing that this should be G2G on OSX/LINUX/WINDOWS

**Comment by pirog** [comment]
@reynoldsalec also updated the docs to reflect the new jam. should be good with my stuff on this issue!
