### ISSUE TITLE
DNS issues in Windows 10 after installing kalabox?

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1480]
After installing and reinstalling kalabox beta 2 latest dev release from yesterday i can no longer reach websites or download emails in Windows 10 home edition.

It seems that some combination of ipconfig /flushdns, ipconfig /release, ipconfig /renew works temporarily, but then I have to do it again.

I have virtualbox, virtualbox 2, and wifi under network connections. Wifi is configured to use Open DNS.

Any thoughts?

**Comment by pirog** [comment]
This should not happen by default but could if you are, for some reason, bridging your internet connection to the VirtualBox network adapter. We set up a DNS server on one of your VirtualBox adapters but these adapters are HOST-ONLY so they should not impact your general internet.

**Comment by pirog** [comment]
going to close this in favor of #1487, pretty sure that is the same issue as this one

**Comment by bmcclure** [comment]
@pirog Every time I go through the Kalabox installer, I seem to go through a period that's very much like this bug report.

I'm experiencing the issue right now and this is the closest bug report I can find to what I'm experiencing, although it may still be related to #1487, it just seems to have different symptoms.

Basically, I installed Kalabox 0.13 RC1, and since then DNS resolution on my host computer goes down constantly. More often than not, DNS resolution is simply not working. If I wait a few minutes, it'll start working again briefly. Alternately, if I disconnect and reconnect from the Wifi network I'm on, then DNS resolution starts working again temporarily for a few minutes.

This has been happening for the past few releases of Kalabox at least and usually after a day or two of messing around with things, reinstalling things, etc. I eventually get things all evened out. But the frustrating part is, I don't ever know what actually fixes it--something that I think worked one time doesn't work the next.

It's making it incredibly difficult to use Kalabox even though I recently finally got it working in general on my computer. It was finally seeming to work well until I tried the new RC1 installer, and since then it's back to the same old DNS issues I keep having to troubleshoot.

I realize this is pretty vague. I've spent days trying to figure out what exactly causes or is related to this issue, so I'm not even really sure what details to include here, or if this is the right place. If I should keep this within the umbrella of #1487 I'm fine with that, I just didn't want to muddy that issue if this is something separate.

**Comment by pirog** [comment]
@bmcclure yeah i share your frustration here because i'd like to know what causes this and also what fixes it. In our test windows environments we have not been able to replicate this at all and things work as expected.

definitely seems like here is a good subset of users who are experiencing this though. I think we should keep all this under #1487 since that seems to have the most detail and is liekly the same thing.

**Comment by jsibley2** [comment]
Isn't #1487 closed, referencing #1478?

In the meantime, could you share a more manual way of installing kalabox, ideally with more debugging options, so that we could help out more easily?

**Comment by bmcclure** [comment]
I posted an update in the other issue to keep things consolidated there. But for anyone looking here, I found a consistent workaround in my case. Your mileage may vary, but here's what I did: https://github.com/kalabox/kalabox/issues/1478#issuecomment-246055838

**Comment by bmcclure** [comment]
@jsibley2 To answer your question specifically from a user's point of view, I think the installation basically consists of putting the Kalabox files in place, then running engine.bat, services.bat, and dns.bat. If you run those .bat files manually after the install is done, you  can see what it's actually doing in the console output.

**Comment by pirog** [comment]
@jsibley2 yeah sorry, #1478! 

@bmcclure yes that is more or less what happens. we are using the time tested innosetup framework for the windows installer. the source is over here and its fairly easy to parse through it to get an idea of what is going on
https://github.com/kalabox/kalabox/tree/v0.13/installer/win32
