### ISSUE TITLE
Should uninstall remove .kalabox directory in Windows?

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1481]
After running uninstall to remove kalabox, .kalabox directory remains. Should the uninstall process remove this directory and the files it contains?

In the meantime, should I assume that it should be deleted manually before installing a new release?

Thanks.

**Comment by pirog** [comment]
@jsibley2 this is a good question. Right now we are not removing it but maybe we should especially because GUI apps get stored in there. 

You do not need to remove the entire directory for a reinstall but for some upgrades you will need to remove preexisting apps. Have you checked out the docs about updating? 
http://docs.kalabox.io/en/stable/users/updating/

**Comment by pirog** [comment]
@jsibley2 so looking into this again i think its probably best practice to not remove user config during an uninstall. That said apps that stick around from a reinstall may not work as expected but we've documented this fairly well over here
http://docs.kalabox.io/en/stable/users/updating/#purge-updating
