### ISSUE TITLE
After install run error: expecting an array, a promise or a thenable

### ISSUE THREAD

**Issue by abea** [kalabox/kalabox#1483]
Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
v0.13.0-beta.2 on OS X 10.11.5

Have you previously installed Kalabox? If so, what version?
I previously had v0.10 installed. I uninstalled it earlier today using the script and manual uninstall instructions.

**Tell us about your bug**

I went to install the new v0.13 beta 2, but initially couldn't because I still had v0.10 hanging around. I ran the uninstall script as directed, removed and deleted the machine from Virtual Box, and confirmed there was nothing in `~/.docker/machine/machines`.

I then downloaded the latest version, ran the installer, and it said that installation completed successfully. I then ran `kbox` from home and got the following error:

```
expecting an array, a promise or a thenable

    See http://goo.gl/s8MMhc

TypeError: expecting an array, a promise or a thenable

    See http://goo.gl/s8MMhc

    at process._tickCallback (node.js:917:13)
```

It seems to be referencing a Bluebird.js error. I uninstalled all again, restarted my computer, and tried again with the same result. I saw similar error in #1176, but I don't have Kalabox installed via npm.

The GUI application also does not seem to be complete. Trying to open that show the error: `You can’t open the application “Kalabox” because it may be damaged or incomplete.`

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
The software dependencies are not clear. I couldn't tell if the software discussed at http://docs.kalabox.io/en/stable/general/engine/ are required before installing Kalabox or if Kalabox has them bundled.

Does this bug prevent you from using Kalabox? Yes.

**Comment by pirog** [comment]
@abea even if you didnt install with NPM this looks very similar to #1176 and is likely the same thing especially if you are upgrading from a version as old as 0.10.x

**Comment by icampana** [comment]
I'm having the same issue, well really worst, because the GUI doesn't even finish loading, I tried uninstalling everything, and reinstalling from zero, I already checked npm packages and there is nothing related to kalabox (as far as I can see).

Checked the virtualbox vm and it is up and running.  The only thing I get to see in the logs is this:
{"action":"error","message":"\u001b[36mMETRICS\u001b[39m\u001b[90m ==> \u001b[39mReporting.","stack":"TypeError: expecting an array, a promise or a thenable\n\n    See http://goo.gl/s8MMhc\n\n    at process._tickCallback (node.js:917:13)","tags":[],"mode":"cli","devMode":false,"version":"0.13.0-beta.2","os":{"type":"Darwin","platform":"darwin","release":"15.6.0","arch":"x64"},"nodeVersion":"v0.10.40","created":"2016-07-26T23:37:36.811Z","level":"debug","timestamp":"2016-07-26T23:37:38.080Z"}

And that matches the description.  By the way I'm using fish as my default shell, I'm including that because it was also a problem during installation, I had to switch back to bash to be able to install, I'll try to switch back now to test this too.

**Comment by pirog** [comment]
@icampana yeah i would def be interested in switching shells matters. right now there are a few issues when installing with a non-bash shell as the default
https://github.com/kalabox/kalabox/issues/1343

**Comment by abea** [comment]
Thanks, @pirog. I'll give it another shot and follow-up.

**Comment by pirog** [comment]
Awesome. It also would be great if you guys could paste what NPM modules you have installed globally. @abea @icampana.

**Comment by icampana** [comment]
@pirog after removing absolutely everything, first used the uninstall script bundled inside the package, removed the .kalabox directory, and the virtual box VM, then I decided to reinstall from scratch once again with the new beta, and it worked perfectly, even without switching back to bash, seems like the problems are gone (hopefully).

It's looking great!

**Comment by pirog** [comment]
awesome and great to hear!

**Comment by abea** [comment]
I think I'm all set here. I was making sure that the `~/.docker/` subdirectory was gone, but I don't think I think the `.kalabox` directory had been hanging about. I see the new version isn't a hidden directory. Removing that old one seems to have done the trick. I'm also using Beta3, though that may be less of the solution.

Cheers!
