### ISSUE TITLE
Getting xdebug to work with phpstorm and kalabox

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1507]
I'm unclear about how much setup I need to do to get xdebug to work with phpstorm and kalabox.

The message I'm getting now is "Debug session was finished without being paused. It may be caused by path mappings misconfiguration or not synchronized local and remote projects. To figure out the problem check path mappings configuration for 'appserver' server at PHP|Servers or enable Break at first line in PHP scripts option (from Run menu).

I think that this is at least one place I need to add some details:

![image](https://cloud.githubusercontent.com/assets/6576953/17272938/214ab61e-5672-11e6-985a-8d9718945f00.png)

**Comment by jsibley2** [comment]
I believe that the issue is that the IDE is looking for the location of the php executable.

Am I correct that the php executable is run as a service within appserver, so there aren't necessarily local files with php.exe, etc.?

If so, is there a better process than:
- check php version (e.g., in phpinfo())
- download and install that version on local computer
- configure IDE to use this php interpreter

Thanks.

**Comment by pirog** [comment]
@jsibley2 location of the php executable should not matter. xdebug is typically run as a remote service and i personally have never seen this as required info in any IDE i have used in the past. 

Have you looked at this?
https://confluence.jetbrains.com/display/PhpStorm/Zero-configuration+Web+Application+Debugging+with+Xdebug+and+PhpStorm

or this?
https://github.com/kalabox/kalabox/issues/202

**Comment by reynoldsalec** [comment]
@jsibley2 @ashday I was able to get debugging working in PHPStorm by using the default settings:

![screen shot 2016-09-23 at 11 34 21 am](https://cloud.githubusercontent.com/assets/1153738/18797210/b9166f58-8181-11e6-8810-9874fcd8099d.png)

After clicking the button "Start Listening for PHP Debug Connections" and creating a breakpoint (I just put one in my index.php file), I initiated a connection by requesting my site in Chrome with the XDEBUG_SESSION_START parameter: http://kalabox-drupal7.kbox/?XDEBUG_SESSION_START=1

PHPStorm immediately popped up with this window; these defaults it provided me were correct:

![screen shot 2016-09-23 at 11 31 20 am](https://cloud.githubusercontent.com/assets/1153738/18797297/356272fa-8182-11e6-8cd6-dd5987ce14e7.png)

After this, my breakpoint halted execution and I was receiving variables:

![screen shot 2016-09-23 at 11 32 46 am](https://cloud.githubusercontent.com/assets/1153738/18797328/5782abca-8182-11e6-8b6b-d39e7b58fc31.png)

The one thing I'm curious about is the error message you can see in the above screenshot; I'm not sure where /src/config/php/prepend.php is coming from. @pirog if you have any clues on that would be curious, but it doesn't seem to have any impact on debugging.

The other catch I've seen pop up in other issues is that people already have DNSmasq running on port 9000 and that can disrupt xdebug, so could be something to look into if you're still having issues.

If this is helpful, I can add it to our Docs.

**Comment by pirog** [comment]
@reynoldsalec `prepend.php` is loaded by the `php.ini` and it contains the PANTHEON env config. It SHOULD exist locally in APP_ROOT/config/php/prepend.php. Not sure if you can set that somewhere or not.

**Comment by mikeethedude** [comment]
This might also be useful to note here. We typically use the tools in PHPStorm a little differently I guess. I set it up to work so that clicking the little bug icon under Run->debug(named service) would launch the xdebug session in your chosen browser.


Under Preferences-> Languages & Frameworks -> PHP

I had to set the path mapping for the code directory and the php/prepend.php file.

![image](https://cloud.githubusercontent.com/assets/15275301/18797881/d336aabc-8184-11e6-92b5-6b5b83166dba.png)

Then going to Run->Edit Configurations

You hit the + at the top left and add a new PHP web Application.

![image](https://cloud.githubusercontent.com/assets/15275301/18798025/63f79b56-8185-11e6-8222-591300b9f947.png)

That's all there was to it for me. I added some breakpoints and hit this icon. 
![eiq_portal_module_-_cgt_-_____kalabox_apps_cgt_](https://cloud.githubusercontent.com/assets/15275301/18798090/9e384234-8185-11e6-8d78-7efa98f55cac.png)

**Comment by jsibley2** [comment]
Thank you for trying this and documenting it.

So, one thing that wasn't clear to me was that I should choose the top directory of the Pantheon application, and that I shouldn't start at \code, as that wouldn't let me set the mapping for prepend.php, and phpstorm would complain.

I think that the problems I was having previously might have been related to some DNS issues that seem to have been taken care of. Sometimes, it would work, and sometimes nothing I did seemed to make a difference.

Thanks again!

**Comment by pirog** [comment]
Anyone game here to submit a PR to get this in our Pantheon docs?
https://github.com/kalabox/kalabox-app-pantheon/blob/v2.0/docs/users/tooling.md#xdebug

Might be good to flesh out the sublime text instructions as well @reynoldsalec

**Comment by pirog** [comment]
Just for ref here is some working xdebug config for ST

```json
"settings":
	{
		"xdebug":
		{
			"max_children": 32,
			"max_depth": 16,
			"path_mapping":
			{
				"/code/": "/Users/pirog/Desktop/apps/webspark/code/"
			},
			"port": 9000,
			"pretty_output": true,
			"url": "http://webspark.kbox/"
		}
	}
```

**Comment by pirog** [comment]
Alright! this should be in the pantheon docs now!

**Comment by bmcclure** [comment]
Minor thing I came across: I didn't want to move my PhpStorm project up one directory, I wanted it to be in /code so that my .idea directory could be version controlled with the project.

I discovered that by going to Settings > Directories, you can click Add Content Root on the right of the directory list and add the "config" directory to the project separate from the /code directory. This then allowed me to map the path to prepend.php properly and Xdebug is working great!

**Comment by gravypower** [comment]
For anyone who comes across this while googling, [this video](https://www.youtube.com/watch?v=Km6BcuzZuys) helped me get debug working with phpstorm.

**Comment by ashzadeh** [comment]
I have it working as described here but prepend.php is trigged on every refresh if I'm debugging. Anyone know why?

**Comment by mortona42** [comment]
I mapped /code on the box to my site dir in Kalabox, but same as above.

**Comment by bradchesney79** [comment]
Nice @pirog , for shoving in a PHP interpreter into PHPStorm-- I ended up with this:

https://stackoverflow.com/questions/44330629/how-to-load-old-php-versions-for-phpstorm-but-not-install-them-on-your-local/44335102#44335102

**Comment by ccharlton** [comment]
HTTPS support?
