### ISSUE TITLE
Repeated unison.tmp files dirtying git

### ISSUE THREAD

**Issue by abea** [kalabox/kalabox#1559]
Bug Report
==========

Kalabox version: 0.13.0-beta.3
OS: OS X 10.11.6
Have you previously installed Kalabox? Yes. 0.11, I think but cleared it all out extensively to install 0.13.

**Tell us about your bug**
Git with Kalabox differs from regular git statements. `kbox git status` showed `.unison..gitignore.5a6c75d3de2d82158f3a507820c5e854.unison.tmp` as untracked. I didn't know the file and couldn't find it, so I ran `kbox git checkout
.unison..gitignore.5a6c75d3de2d82158f3a507820c5e854.unison.tmp`. After that, two files that had also been dirty only on `kbox git` that I'd checked out suddenly showed with variations in normal git as:

```
sites/origineight/modules/contrib/token/css/.unison.jquery.treeTable.css.5a6c75d3de2d82158f3a507820c5e854.unison.tmp
sites/origineight/modules/contrib/token/js/.unison.jquery.treeTable.js.5a6c75d3de2d82158f3a507820c5e854.unison.tmp
```

I can't delete or check these out without them reappearing less than a minute later.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Started up GUI and Pantheon site instance.
2. `cd code`
3. `kbox git status`
4. `kbox git checkout [hidden unison file]`
5. `git status`

**Does this bug prevent you from using Kalabox?** Yes.

**Comment by abea** [comment]
I temporarily solved by excluding `*.unison.tmp` in my local .git directory. I'm still seeing the new files in my codebase, though.

**Comment by bmcclure** [comment]
In my case when I start syncing a large number of changes, I get one or more *.unison.tmp files in my code directory, but as the syncs complete (could take several minutes) the files seem to go away on their own. I assume this is just the standard functionality of Unison's temp files.

On one site I seemed to have an issue with files missing from git and those .tmp files not going away, but restarting the kalabox app seemed to force unison to continue syncing. I ended up having to restart it a couple of times, and since then it's been fine.

I'm on Windows 10, and this may be totally unrelated to the bug reported here, but just wanted to add my experience.

**Comment by abea** [comment]
Yeah, this might be nothing serious. A couple of days later I'm not seeing those files anymore. I am seeing two different dirty files with `kbox git status`. These two would have been generated by a module in the last hour or so.

It's a weird thing to have happen, but I'm not sure what if anything needs to be done. I guess I'll close for now.

**Comment by pirog** [comment]
@abea its possible these files are just taking a second to sync.
