### ISSUE TITLE
allow local.example.com domains

### ISSUE THREAD

**Issue by OddenCreative** [kalabox/kalabox#1611]
Feature Request

using example.kbox works great at spinning up sites, but if we can create a custom top level domain easily, we can improve the workflow that allows our sites to work like the live environment. 

e.g. - TypeKit uses a domain authorization that we can specify www.example.com, example.com, and *.example.com.

Adding in local.example.com would allow a simplification into the workflow, and when adding this across multiple services can cut down the potential problem children in complicated development teams.

**Comment by pirog** [comment]
@OddenCreative since we don't use `/etc/hosts` i'm not exactly sure how we would do this easily eg something configurable in `kalabox.yml`

We currently use the `hipache` reverse proxy and `dnsmasq` to map `*.kbox` domains to `SCHEME://IP:PORT` eg `http://10.13.37.100:32764`. I'm not sure how we could add preexisting TLDs like `*.com` reliably into the mix here without introducing some potential chaos to the users.

Are there other kinds of workflows or logix where you need `local.example.com` beyond TypeKit (or things that work like TypeKit)?

Is it not possible to add something like `*.kbox` to TypeKit?

**Comment by OddenCreative** [comment]
It can be done, but it gets messy and I'm trying to keep a level of stability in the dev, deploy process to keep people from making to many mistakes...

**Comment by OddenCreative** [comment]
A thought to be had...

If a secondary domain could be created in the kbox instance, those with the know, can put in their own mapping for IP if the kbox can handle the domain name response...

A thought

**Comment by pirog** [comment]
@OddenCreative i had considered something like that, and it IS easy enough to allow our DNS system to handle some additional external requests. The big thing is we would need to coordinate non *.kbox domain updates to both dnsmasq and our proxy because we need both an IP and a PORT to do a mapping from domain to service.

Have you tried editing the kalabox dns container config file along the lines of
http://serverfault.com/questions/420689/how-to-enforce-dnsmasq-to-use-dns-for-some-hosts

If you could get the dnsmasq container to refresh with the correct settings if kalabox detects non *.kbox domains in an apps kalabox.yml file you might be able to get the func you want.

**Comment by OddenCreative** [comment]
as while I am digging through this, I am going through the dockerfiles. Is there a map of the variables in the docker yml?

e.g. - $KALABOX_APP_PHP_CONFIG_IMAGE

**Comment by pirog** [comment]
http://docs.kalabox.io/en/stable/users/cli/#env

**Comment by OddenCreative** [comment]
Interestingly, there is nothing that maps the $KALABOX_APP... to something in the documents... Or I'm missing it... I've been crawling code, and documents trying to figure out where it is set, or what maps the info...

**Comment by pirog** [comment]
its probably going to be in the code for the php plugin not in kalabox core directly.

**Comment by OddenCreative** [comment]
all that digging, and all I had to do was put in kbox env... 🙄

**Comment by pirog** [comment]
@OddenCreative so this is going to be possible (although you'l have to edit your /etc/hosts files to do it) in the next release.
