### ISSUE TITLE
Unisom seems to have stopped syncing

### ISSUE THREAD

**Issue by bmcclure** [kalabox/kalabox#1621]
I am using 2.0 on Windows 10 Pro. It seemed to be working OK yesterday, however today I'm experiencing an issue with my changes making it to the VM.

I keep changing code, but the changes never seem to sync (they never show up on the site or with `kbox git status`). I've restarted the app, I've restarted kbox, I've restarted my computer, but it seems to have just stopped syncing. Is there somewhere I can check to troubleshoot what might be happening?

**Comment by bmcclure** [comment]
I'm not sure what caused this, however `kbox rebuild`, followed by waiting a few minutes after it was done for the files to sync, seems to have solved things.

**Comment by pirog** [comment]
@bmcclure hmmm yeah, not sure without more info. i know that unison is pretty reliable and stable (and is set to autorestart on a crash). I think the two biggest things that would cause a slow sync (or no sync at all) are

1. Syncing a decent amount of files and having to wait for the queue to clear out
2. Forgetting your sync settings in `kalabox.yml` and then expecting an ignored directory of file to sync.

If this happens in the future i would try to get at the docker logs for the unison container for the offending app as documented here. 
http://docs.kalabox.io/en/stable/troubleshooting/#docker-logs

specifically `docker ps --all` to ensure the container is running and `docker logs` to print out any specific errors.

**Comment by dougvann** [comment]
Same issue for me. Kbox 2.1.3 on Mac Sierra 
My unison container is running and the logs show that the sync occurs only when the container is booting. Oooh. Another test reveals that if I kbod drush dl [anything] then the unison runs and synchs perfectly.
However an edit to a theme file or adding a whole library only gets synced if I stop/restart the contaier.
Even when I have file edits, if I drush a new module or theme down, only that new project is synced, the other new or edited files will notsync unless I stop/restart.
**Wuzzup w/ dat?**
**_Logs appear below:_**
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
Contacting server...
Looking for changes
new dir  ---->            themes/custom                                 
Reconciling changes
Propagating updates
UNISON 2.49.543 (OCAML 4.02.3) started propagating changes at 20:24:00.74 on 06 Apr 2017
[BGN] Copying themes/custom from /kalashare/code to /code
[END] Copying themes/custom
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 20:24:00.75 on 06 Apr 2017
Saving synchronizer state
Synchronization complete at 20:24:00  (1 item transferred, 0 skipped, 0 failed)
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
Contacting server...                                                    
Looking for changes
                         Reconciling changesnterface.php                
Propagating updates
changed  ---->            themes/custom/mytheme/mytheme.info.yml        
UNISON 2.49.543 (OCAML 4.02.3) started propagating changes at 20:33:00.69 on 06 Apr 2017
[BGN] Updating file themes/custom/mytheme/mytheme.info.yml from /kalashare/code to /code
[END] Updating file themes/custom/mytheme/mytheme.info.yml
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 20:33:00.70 on 06 Apr 2017
Saving synchronizer state
Synchronization complete at 20:33:00  (1 item transferred, 0 skipped, 0 failed)
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
Looking for changes
Reconciling changes
Propagating updates
UNISON 2.49.543 (OCAML 4.02.3) started propagating changes at 20:36:17.94 on 06 Apr 2017
[BGN] Copying themes/adminimal_theme from /code to /kalashare/code
         <---- new dir    themes/adminimal_theme                        
[END] Copying themes/adminimal_theme
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 20:36:18.03 on 06 Apr 2017
Saving synchronizer state
Synchronization complete at 20:36:18  (1 item transferred, 0 skipped, 0 failed)
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
Looking for changes
         <---- new dir    themes/adaptivetheme  
Reconciling changes
Propagating updates
UNISON 2.49.543 (OCAML 4.02.3) started propagating changes at 20:38:36.92 on 06 Apr 2017
[BGN] Copying themes/adaptivetheme from /code to /kalashare/code
[END] Copying themes/adaptivetheme
UNISON 2.49.543 (OCAML 4.02.3) finished propagating changes at 20:38:38.58 on 06 Apr 2017
Saving synchronizer state
Synchronization complete at 20:38:38  (1 item transferred, 0 skipped, 0 failed)
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.

**Comment by pirog** [comment]
So definitely not the expected behavior. Should be bidirectionally syncing
continuously.

I think the most common reason Ive seen for what you are describing is when
the user has moved their home directory to somewhere outside of /Users eg
an external disk mounted volume. I would explore whether your set up is
like this and be careful of potential symlinks that may obscure the actual
location of your home folder.

If/once you discover the directory you'll want to go into the docker UI and
add it to the list of mounted/shared folders.

**Comment by dougvann** [comment]
Thanks for th eideas, Mike.
My Kbox projects are at ~/Kalabox/[project-name]
With code obviously residing at ~/Kalabox/[project-name]/code
The fact that code syncs on bootup suggests to me that it CAN sync but for some reason isn't "looking that hard" at other times. That sounds preposterously like Kalabox achieving self awareness and choosing arbitrarily when to sync? So we can strike that solution off of the list.... Or can we!?

But seriously... I dunno why it can't sync up. From /code/ all the way down the chmod = 755 and the chown is the same as all other files.
And where is the Docker UI you referenced? I can interact with current projects, or start new ones, check errors messages, or shut the whole thing down. Beyond that there is no Kalabox UI that I can see.
Will DEF try this on another Mac when I fly back home to see if I get the same issues there. For now, I'm hosed. :-(

**Comment by pirog** [comment]
So what you want to determine is where ~ points to.

Docker UI should be the little whale icon in the top bar.
