### ISSUE TITLE
Windows 10 uninstallation

### ISSUE THREAD

**Issue by jsibley2** [kalabox/kalabox#1624]
When removing Kalabox through Windows 10, there is a message along the lines of "some files could not be removed, please remove them manually."

Could the uninstaller possibly let the user know what wasn't able to be removed?

I found the following and removed them:

Kalabox\bin\docker-machine (I was prompted for granting admin access when removing Kalabox)
.kalabox (including apps and a lot of other files)
.virtualbox (looked like mostly log files)

Does the documentation specify what can safely remain (if anything)?

**Comment by pirog** [comment]
@jsibley2 this message comes from docker-machine so you would want to post an issue about this over there. My suspicion is that it is intentionally vague because its likely impossible for it to know all the possible places these things could be installed on a windows box.

The documentation does not state what can safely remain for same reasons as above.
