### ISSUE TITLE
Git permissions issue with kbox

### ISSUE THREAD

**Issue by jserrao** [kalabox/kalabox#1651]
Version
v2.0.1 on OSX 10.11.06

Any attempt to write/commit to my repo (`kbox git add .`) results in:
`error: insufficient permission for adding an object to repository database .git/objects`

`git add .` works fine, which makes me think the kbox user can't see the repo somehow. I tried `chmod` to open stuff up just as a test but not even `777` yielded anything. I think this might be a issue with how the kbox user communicates with the docker images, which is beyond me.

FWIW, I wasn't having any problems until I upgraded to v2.x and stability has taken a huge nosedive for me in regards to Kalabox in general. It's also slowed down tremendously (even post reinstall). Not sure what's going on.

**Comment by pirog** [comment]
@jserrao haven't seen this before. Is this happening on all your apps?

v2.x is definitely more stable and performant so im wondering if something went wrong for your  upgrade or reinstall. I would make sure you are following all the instructions for doing a full reinstall. This is going to include recreating any apps you installed with previous versions.

**Comment by jserrao** [comment]
@pirog - still chasing this one down but it has to do with adding another `git remote` and mismatched SSH keys. It only cropped up when I pushed the repo out to github and added that second remote. When the kalabox repo gets initialized I think it's using not my default SSH but a kalabox-specific one that communicates with Pantheon. 

I'll let you know if I can recreate and give guidance afterwards about solutions.

**Comment by pirog** [comment]
@jserrao ok this makes a little more sense to me now.

So yeah, we will create and manage an ssh key for you when we spin up the pantheon account. This is so you can seamlessly interact with pantheon. The key pair for that can be found at `~/.kalabox/pantheon/keys`. Every command you run with `kbox git` is going to use this key. 

Def understand and appreciate the multi-remote workflow but it's not explicitly supported by Kalabox at this time. That said you can work around this fairly easily in a few ways

1. Add the public part of your pantheon key in `~/.kalabox/pantheon/keys` to the whatever extra remote you are using. This will ensure `kbox git` can communicate with both remotes.
2. Use regular `git` as opposed to `kbox git` so that it is loading your default ssh key.

Let me know if that helps!
