### ISSUE TITLE
Lockr Integration

### ISSUE THREAD

**Issue by cellar-door** [kalabox/kalabox#1694]
At the current moment, Lockr users do not have a good way to manage their local development environment when it comes to syncing keys. We are proposing to have certificates used in the authentication to Lockr available to the local environment so users can securely authenticate to Lockr and access development keys.

Initially we can roll this out fairly quickly on Pantheon by doing the following:
1. Using the sftp connection information found with the terminus command `terminus connection:info [SITE].dev --field "SFTP Command"`
2. Once connected with the information from step 1, the client would download the certs/binding.pem to a location that matches `/srv/bindings/' . PANTHEON_BINDING . '/certs/binding.pem` and set the permissions on it to read only.

Once this initial Pantheon specific usecase is done, we can then explore customized certificates issued directly from Lockr for other non-Pantheon sites.

**Comment by pirog** [comment]
@cellar-door we've actually got some budget for something like this in our next sprint so i'm going to propose we do a PoC on this for 2.1.1 because the code DIFF might be worth a thousand words for whomever is going to to help with this on the Lockr end.

What would be good for us is a brief description of how we can test this locally? Is it sufficient to grab https://www.drupal.org/project/lockr and just verify that it can read the key?

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox-app-pantheon/pull/188
