### ISSUE TITLE
KBox dependency on same IP address? Broken Drupal 8 Demo (Related to closed Issuse #1327)

### ISSUE THREAD

**Issue by deborah-ufw** [kalabox/kalabox#1733]
1. Get a Drupal 8 site up and running on Pantheon free level.
2. Push it to Test.
3. Pull the Dev (not Test) into Kbox.
4. Follow normal development flow, pushing and pulling between Kbox dev and Pantheon dev.
5. Go to CEO's house to present the Drupal 8 site in Kbox.

**Expected result:**
Kbox can present the Drupal 8 site in the browser with full functionality as it did an hour ago at my house.

**Actual result:**
mysite.kbox’s server DNS address could not be found.

Request:
1. Kbox should have a statement in the Kbox window that IP address change will break the Kbox instance in the browser -- and that user should push to Dev prior to any disconnection.

2. Kbox should not be IP dependent. There should either be a behind-the-scenes process to re-connect or re-create the Kbox instance on IP change, or else a button to press to execute a re-connect.

**Comment by pirog** [comment]
Kbox is 100% not IP dependent

**Comment by pirog** [comment]
@deborah-ufw its worth mentioning that newer kalabox versions are going to have an address like `name.kbox.site` as opposed to `name.kbox` so that might be your issue.

**Comment by deborah-ufw** [comment]
A previous issue seemed to suggest there was an IP dependency. It was just a guess on my part. Why did it break? There was no other change - just location and different wireless connection.

**Comment by pirog** [comment]
@deborah-ufw #1327 deals with a DNS server we were running internally to resolve domains properly. For various reasons, mostly regarding how Windows handles DNS, we've changed the implementation so that `*.kbox.site|host` is now resolved by the internet like any other domain e.g. `google.com`.

I'd read up on https://github.com/kalabox/kalabox/issues/1736 which might have been what happened to you. Sadly there is not much we can do about that since we can't directly (and more importantly shouldnt) change user's router config. There is a workaround posted in #1736 though.
