### ISSUE TITLE
Error from Notification - Win 10x64

### ISSUE THREAD

**Issue by wesruv** [kalabox/kalabox#1758]
Tag: bug, Windows10

Bug Report
==========

**Tell us about your setup**

What is your Kalabox version and operating system?
2.1.3

Have you previously installed Kalabox? If so, what version?
Yes, looks like it 2.1.0 before

**Tell us about your bug**
Spun up a D8 site from Kalabox, got db connection details, site's working great, got this error in a notification. Doesn't seem to be an issue preventing me from using the tools, just a nasty looking error.

> Error: [ngModel:nonassign] Expression ''mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database' is non-assignable. Element: <input ng-model="'mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database" readonly="" select-on-click="" class="ng-pristine ng-untouched ng-valid"> http://errors.angularjs.org/1.4.14/ngModel/nonassign?p0='mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database&p1=%3Cinput%20ng-model%3D%22'mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database%22%20readonly%3D%22%22%20select-on-click%3D%22%22%20class%3D%22ng-pristine%20ng-untouched%20ng-valid%22%3E

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

> Example: 

> 1. Started up GUI
> 2. Clicked on my Pantheon account in the sidebar
> 3. Selected a site and an environment
> 4. Kept the default create options and pressed submit

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Nope

Does this bug prevent you from using Kalabox?
Nope

**Comment by pirog** [comment]
thanks @wesruv! i was wondering when someone would post a ticket about this :)

good news is i think this error is not actually an error; a false prophet of errors, so it **shouldnt** impact usage.

**Comment by magbicaleman** [comment]
I'm having same issue on;
macOs Sierra (10.12.2)
Kalabox v 2.1.3

Happens when I do a database pull, the effect is that the database does not get pulled.

`Error: [ngModel:nonassign] Expression ''mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database' is non-assignable. Element: <input ng-model="'mysql -u ' + db.external_connection_info.user + ' -p' + db.external_connection_info.password + ' -h ' + db.external_connection_info.host + ' -P ' + db.external_connection_info.port + ' ' + db.external_connection_info.database" readonly="" select-on-click="" class="ng-pristine ng-untouched ng-valid"> http://errors.angularjs.org/1.4.14/ngModel/nonassign?p0='mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database&p1=%3Cinput%20ng-model%3D%22'mysql%20-u%20'%20%2B%20db.external_connection_info.user%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2B%20'%20-p'%20%2B%20db.external_connection_info.password%20%2B%20'%20-h%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.host%20%2B%20'%20-P%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.port%20%2B%20'%20'%20%2B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20db.external_connection_info.database%22%20readonly%3D%22%22%20select-on-click%3D%22%22%20class%3D%22ng-pristine%20ng-untouched%20ng-valid%22%3E`

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
