### ISSUE TITLE
Show Pantheon env on Sites screen/info

### ISSUE THREAD

**Issue by ccharlton** [kalabox/kalabox#1777]
It would be nice to easily see which [Pantheon] Environment a "Site" is tied to on the main Kalabox screen. When you have multiple Sites from Pantheon, there's no way to know which "Site" is tied to which "Env".

**Comment by pirog** [comment]
good request. that said you can def name the site so it contains the
environment info eg sitename-env. you also can look at the kalabox.yml
inside of your app.

**Comment by trustypelletgun** [comment]
For Pantheon sites, I would prefer the default behavior to be that the app name matches the chosen environment (updating dynamically when a different env is selected) and then I could manually edit the name if desired before creating the app.

Thinking longer term, it would be nice to have an exposed setting (both in CLI and GUI) to define the app naming template so that one could choose "sitename", "sitename-env", "env", or some other custom template as the default name for new Pantheon apps.

**Comment by ccharlton** [comment]
The display/naming pattern from Pantheon is "SITE.ENV", eg. "example.multidev1", "example.multidev2", "example.dev", "example.test", "example.live", "example.live". Pantheon sites should have parity, otherwise image the confusion people will cause on themselves!

**Comment by pirog** [comment]
Hey all!

We've (not so) secretly been working on a new project called [Lando](https://github.com/lando/lando) which is a completely different kind of local development tool but very much the spiritual successor to Kalabox. For that reason we are no longer actively fixing issues with Kalabox although we are still providing support via our [slack channel](https://slackpass.io/kalabox)

At this point we encourage you to make the switch to Lando, especially if you've posted an issue here in the Kalabox queue. There is a **VERY HIGH CHANCE** that this issue has been addressed in Lando and a **NEAR CERTAIN CHANCE** that it will not be back ported to Kalabox.

Please check out https://docs.lndo.io/ to get rolling with Lando and enjoy!
