### ISSUE TITLE
Syncthing error at end of kbox start

### ISSUE THREAD

**Issue by donkoller** [kalabox/kalabox#188]
syncthing http://127.0.0.1:60008/rest/system/connections (Error: connect ECONNREFUSED)

Is this a problem, or just ignore...?

**Comment by pirog** [comment]
it's a problem in so far as it isn't supposed to do that :) It's not a problem in that running `kbox restart` seems to resolve it.

@bcauldwell added a potential fix for this but it won't roll out until the 0.8.0 version. You could update your kalabox to the dev branch which i can show you how to do if you want but its not recommended since it is a development branch and you'll likely get some other bugs until we fully QA it.

**Comment by donkoller** [comment]
Thanks

Sent from my iPhone6+ (iOS 8)
donkoller@bea-enterprises.com
