### ISSUE TITLE
Code output to screen during install

### ISSUE THREAD

**Issue by UTANdev** [kalabox/kalabox#311]
Back from vacation, I ran a quick `npm install kalabox -g` to get things started and the screen output included some code:
```
C:\Users\UTAN\VirtualBox VMs\mtms-2015>npm install kalabox -g
-
> kerberos@0.0.12 install C:\Users\UTAN\AppData\Roaming\npm\node_modules\kalabox\node_modules\kalabox-metrics-rest\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\UTAN\AppData\Roaming\npm\node_modules\kalabox\node_modules\kalabox-metrics-rest\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
C:\Users\UTAN\AppData\Roaming\npm\kbox -> C:\Users\UTAN\AppData\Roaming\npm\node_modules\kalabox\bin\kbox.js
```

Running on Windows 7, inside cmd2.exe run as administrator.

Comments?

**Comment by pirog** [comment]
Its just output and is normal. Is it producing an error message or anything like that at all?

**Comment by UTANdev** [comment]
No, no error. Since I'm still having trouble getting kbox to install without error (a matter for another issue), I'm fidgety about anything that looks strange. I mean, why would an installer output some random bit of code to the screen? That looks like a bug.

Thanks for confirming that this, by itself, is not a problem. Onward and upward!

**Comment by pirog** [comment]
You would have to ask the npm people since it's their installer :)

On Sat, Jul 18, 2015 at 3:03 PM, UTAN Dev <notifications@github.com> wrote:

> No, no error. Since I'm still having trouble getting kbox to install
> without error (a matter for another issue), I'm fidgety about anything that
> looks strange. I mean, why would an installer output some random bit of
> code to the screen? That looks like a bug.
>
> Thanks for confirming that this, by itself, is not a problem. Onward and
> upward!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/311#issuecomment-122580660>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
