### ISSUE TITLE
KB2 becomes bogged down after about 6 apps are installed 

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#390]
This is an odd one and I am just going to write what I have seen in the last month or so.  When I get to about 6 apps installed in KB2, it starts to render the system almost unusable.  I am not sure if it is syncthing or if it is a VB issue.  As soon as I purge KB2 and start over with 1 or 2 apps, it works flawlessly.  

If you need more details then this, let me know.  I just had to purge my system again this morning and I had 8 apps installed before I purged.

**Comment by bcauldwell** [comment]
We should be able to tell if it's syncthing by shutting both instances down when the bogging down occurs. I'll add detailed instructions of how to do this when I get to the office.

**Comment by bcauldwell** [comment]
To shutdown syncthing,

1 - Go to http://127.0.0.1:60008/ in a browser, in the top right corner
click on actions -> shutdown
2 - Go to http://10.13.37.42:60008/ in a browser, in the top right corner
click on actions -> shutdown

Let me know if that solves the bog.

On Thu, Aug 20, 2015 at 9:31 AM, <ben@kalamuna.com> wrote:

> We should be able to tell if it's syncthing by shutting both instances
> down when the bogging down occurs. I'll add detailed instructions of how to
> do this when I get to the office.
>
> Sent from my iPhone
>
> On Aug 20, 2015, at 7:10 AM, John Ouellet <notifications@github.com>
> wrote:
>
> This is an odd one and I am just going to write what I have seen in the
> last month or so. When I get to about 6 apps installed in KB2, it starts to
> render the system almost unusable. I am not sure if it is syncthing or if
> it is a VB issue. As soon as I purge KB2 and start over with 1 or 2 apps,
> it works flawlessly.
>
> If you need more details then this, let me know. I just had to purge my
> system again this morning and I had 8 apps installed before I purged.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/390>.
>
>


-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
Ick. I can boot up a bunch of apps and see if i can replicate this. Just to clarify @labboy0276 these 6 apps are RUNNING? or do they just exist? Can you share the mix or running to not running that causes this.

**Comment by labboy0276** [comment]
@pirog mixed, sometimes just 1 o 2 apps running, 4 or 5 not running.

**Comment by reynoldsalec** [comment]
In my case I was noticing significant syncthing CPU usage (90-120%). @bcauldwell checked it out and it looks like a bunch of apps that were "kbox uninstalled" are still running in syncthing. Certainly seems to be the root of some of my performance issues.

**Comment by pirog** [comment]
funny you mentioned this because i just ran into #347 which seems to be the
root issue here

On Tue, Aug 25, 2015 at 12:31 PM, reynoldsalec <notifications@github.com>
wrote:

> In my case I was noticing significant syncthing CPU usage (90-120%).
> @bcauldwell <https://github.com/bcauldwell> checked it out and it looks
> like a bunch of apps that were "kbox uninstalled" are still running in
> syncthing. Certainly seems to be the root of some of my performance issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/390#issuecomment-134709429>.
>



-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
