### ISSUE TITLE
SolR doesn't seem to be indexing

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox#503]
10.x on the binary:

SolR is not indexing (albeit I get the green statuses in the dashboard here admin/config/search/pantheon/)

this error too:

```
john@kalamuna:~/kalabox/apps/huddle-solr$ kbox drush cc all
WD pantheon_apachesolr: Error SSL certificate problem: self signed   [error]
certificate connecting to
https://solr.huddle-solr.kbox/sites/self/environments/kalabox/index/admin/luke?numTerms=0&wt=json
on port 449
WD Apache Solr Views: "0" Status: Request failed                     [warning]
'all' cache was cleared.                                             [success]
john@kalamuna:~/kalabox/apps/huddle-solr$ 
```

**Comment by pirog** [comment]
Hmmm, let me check this out.

**Comment by pirog** [comment]
I am getting all sorts of crazy errors just trying to run this site. 

PIROBOOK1:huddle mpirog$ kbox drush uli
http://localhost/user/reset/1/1442872854/2RCm4F2CikYiEcwydm_33QDqtewq6x5Bwag6lHnYKQ0//login
PIROBOOK1:huddle mpirog$ kbox drush uli
WD php: EntityFieldQueryException: Entity match_redirect has no base [error]
table. in EntityFieldQuery->propertyQuery() (line 1247 of
/code/includes/entity.inc).
Drush command terminated abnormally due to an unrecoverable error.   [error]
EntityFieldQueryException: Entity <em class="placeholder">match_redirect</em> has no base table. in EntityFieldQuery->propertyQuery() (line 1247 of /code/includes/entity.inc).

**Comment by pirog** [comment]
Going to try out SOLR on playbox instead. At least that way we know its an issue with huddle.

**Comment by pirog** [comment]
So solr seems to work fine on playbox. going to go out on a limb and say there is something wrong on huddle.
