### ISSUE TITLE
Wondering where /media is! /sites/default/files -> /media symlink for Drupal on Panthon

### ISSUE THREAD

**Issue by madchops1** [kalabox/kalabox#564]
May be a dumb question but where is this elusive /media directory. I can't find it even when I ssh into Docker container....

**Comment by pirog** [comment]
So `/media` should exist inside the every container for your app. 

Right now in order to access it you need to ssh into the VM and then exec into the container you want. 

```
boot2docker --vm="Kalabox2" ssh (pw: tcuser if needed)
docker ps --all (lists your containers)
docker exec -i -t CONTAINER_NAME bash
cd /media
```

As you might imagine these are not "supported" use cases at this time. That said, we have a feature planned (https://github.com/kalabox/kalabox/issues/511) for the coming months to get `/media` shared out into the correct location on the users host machine so you can access that stuff directly on your Mac, Windows or Linux machine and not inside the VM/container.

You can also remove the appropriate entry from the `shareIgnores` array in the `kalabox.json` file for your app and then `kbox restart` your app. This will sync your media out into the normal location in your `code` folder. **This should be done with extreme caution as very large media directory can cause from pretty weird chaos**

**Comment by madchops1** [comment]
Thanks that helps a lot in understanding whats going on behind the scenes in Kalabox. I appreciate it!!

**Comment by pirog** [comment]
Going to close this in favor of #511
