### ISSUE TITLE
Site add modal form

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox#610]
Now that site add works we need a modal form to collect data from the user about how to create the site.

We'll need to collect the following information, some of which will be based on choices gathered from previous information gathered.

- what to call the site
- which environment to use
- the directory the site should be created in (optional)

**Comment by bcauldwell** [comment]
@reynoldsalec Should I assign to you?

**Comment by reynoldsalec** [comment]
Modal form needs following fields:

- Choose environment you wish to clone. (select dropdown)
- Choose app name. (text)

**Comment by reynoldsalec** [comment]
Ok, the basic modal is up here, talked with @bcauldwell and he needs to provide the environments that are available for each site. I think this is at a decent point for hand-off, so I'll re-assign to Ben, but here are some things I know will need to get completed:

- provide environments available for the site being added
- finalize the site pull process
- how are we going to incorporate dialogues regarding site whether to pull from backup/etc? (probably a new card, after we move to doing this dialogue in the sidebar instead of modal)
