### ISSUE TITLE
Sometime on windows when there is a second VB HO Adapter we can't set the Kalabox HO IP correctly.

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#630]

**Comment by pirog** [comment]
This happens ONLY if the other HO Adapter shares either the IP/DNS with the other aka both adapters cannot have the same address.

**Comment by pirog** [comment]
Presumably this would happen on mac/linux as well.

**Comment by bthompson-mindgrub** [comment]
I just ran into this issue today as well on a fresh install of 0.10.5-alpha5 on Windows 10.

For me, the error occurred in the "Pulling Images" step of kbox update.  Kalabox was unable to pull any of the docker images with an ECONNREFUSED error message.  What perplexed me (and took me a while to track down) was the fact that my B2D VM did have internet connectivity and was able to pull docker images when SSHed into the Kalabox B2D vm using the `docker pull kalabox/dnsmasq:v0.10.0` command.  I eventually fixed this issue by disabling all but one of my HO adapters in Windows Network Connections and updating the network settings (in VirtualBox) to use the remaining network I had left enabled.

Is it possible to just add a warning to the FAQ about this or a check during installation telling the user what to do?  TBH, I saw this issue when trying to troubleshoot my problem but didn't put 2 and 2 together to realize that not being able to set a HO IP correctly was going to cause issues with pulling images.  It wasn't until I had solved my problem that I realized this issue applied to me.

**Comment by pirog** [comment]
Awesome to hear this can actually work on Win10 since we haven't really tried that out yet!

I *think* this happens when you have another host only adapter that is also set to 10.13.37.1. @bthompson-mindgrub can you look at your other adapters and see if any of them are set to that?

Currently we do a check during install to see if your host only adapter has the correct IP, however, if one of your other adapters already has been assigned the same address then this fails... hence this issue. Do you have any suggestions on how we can mitigate this? Presumably if you have another adapter already set for 10.13.37.1 its probably from a previous kbox install attempt so maybe we can safely remove or disable that adapter?

**Comment by bthompson-mindgrub** [comment]
Only other issue I've had on Win10 (so far) is DNS resolution isn't working.  I *think* that might be related to this original adapter problem but I don't want to muddle this issue with it until I do more troubleshooting and see what the resolution is.  If I modify my hosts file, all works beautifully.

@pirog I checked my other adapters and none of them had an IP set for 10.13.37.1.  However, I'm not sure if my test is valid because I previously disabled all of them when troubleshooting this issue and I'm not sure if that cleared out the IPs that were set.

In terms of mitigating this issue, I have 2 different thoughts each with their own pros and cons:

1.  Add an install check that runs `VBoxManage list hostonlyifs` (https://www.virtualbox.org/manual/ch08.html#vboxmanage-list) and then grep/count the number of times "Guid:" appears in the results.  If the string appears more than once, throw an error and direct users to some sort of online documentation about what to do.  I think this is the quickest solution if we are trying to push to a stable release.  It also leaves the complex part up to the user who is (presumably) technically savvy if they've been running Kalabox previously.  The negative of this solution is it requires the user to manually take action and users might still not know what to do, even with online documentation.

2.  On install, create a new HO adapter called "Kbox" and give it the 10.13.37.1 address.  If that address is already used by another adapter, disable said adapter and then finish provisioning the Kbox adapter.  Then assign the Kbox adapter to the B2D vm and always use the Kbox adapter going forward.  This idea makes the assumption that VB gives us a way to assign adapters to VMs by name.  Advantage of this solution is that it is completely seamless to the user and they have to take no action outside of `kbox update`.  However, it seems significantly more complex to code for which will take time and possibly introduce other issues/regressions.

**Comment by pirog** [comment]
There is another open issue on some DNS weirdness over at https://github.com/kalabox/kalabox-app-pantheon/issues/44 if you want to give that the ole look-see. 

Both 1 and 2 seem pretty reasonable. Ideally 2 would be awesome to do and after some cursory research i think it is possible for that to happen. 

Good news is i think there are basically two big issues left. This one and another (possibly related) regarding DNS. 

I'm going to mark this as mission critical and move into the next sprint.

**Comment by bthompson-mindgrub** [comment]
I looked at kalabox/kalabox-app-pantheon#44 but what I was seeing was different.  For me, I couldn't resolve <site-name>.kbox.  Fixing the DNS servers on my HO adapter resolved the issue so I'm willing to just write it off as another symptom of this issue.

**Comment by pirog** [comment]
Got it. Agreed with your diagnosis here. 

I'm spec-ing out a better workflow for setting up the hostonly adapter and i think i've got a pretty good way we can get this done for the alpha6.

**Comment by pirog** [comment]
Ok. So tackling this now. I think the lowest barrier to entry solution for now is

1. Grab the KB2 GUID
2. Wait until after B2D sets up a Host-Only Adapter for KB2
3. `VBoxManage list hostonlyifs` and see if there is an adapter with 10.13.37.1 that is NOT our GUID
4. Remove or disable that adapter if it exists
5. Normally scheduled programming
