### ISSUE TITLE
Error during installation on Windows 7

### ISSUE THREAD

**Issue by angarsky** [kalabox/kalabox#642]
Hi!

I spent all my day in attempt to run kalabox. Script fails in this place: http://screencast.com/t/payKBl2Al.
"TypeError: Object function lodash(value) { ... } has no method 'round'"

Seems, that my issue is connected with #594.
My environment: WIndows 7, Virtual Box 5.0.8. I tried to install alpha-4 and then alpha-3 - I've got same errors.

Is there a way to run Kalabox? What am I do wrong?

**Comment by pirog** [comment]
Don't think you are doing anything wrong.

#594 should be fixed in alpha5 which should be out either Friday or
Saturday.

On Wednesday, October 28, 2015, angarsky <notifications@github.com> wrote:

> Hi!
>
> I spent all my day in attempt to run kalabox. Script fails in this place:
> http://screencast.com/t/payKBl2Al.
> "TypeError: Object function lodash(value) { ... } has no method 'round'"
>
> Seems, that my issue is connected with #594
> <https://github.com/kalabox/kalabox/issues/594>.
> My environment: WIndows 7, Virtual Box 5.0.8. I tried to install alpha-4
> and then alpha-3 - I've got same errors.
>
> Is there a way to run Kalabox? What am I do wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/issues/642>.
>


-- 

Mike

-- 
Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>
, Linkedin
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>,
and Facebook
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9>

**Comment by pirog** [comment]
@angarsky i would try this with the new alpha5 we released yesterday and see if you get the same error. try running it with verbose mode on aka `kbox create pantheon -- -v` so we can capture any rage if it errors again. 

going to close but please reopen if the issue persists.
