### ISSUE TITLE
Support request:  Accessing kbox sites across lan from other devices

### ISSUE THREAD

**Issue by pi-ron** [kalabox/kalabox#707]
Hi Guys,

Just a bit of a support request here...  Can you please give me some direction on if it's possible and how I could go about accessing kalabox sites from other devices ie. iPhones etc, across my LAN?

**Comment by pirog** [comment]
So by default we are using a host-only adapter for the VM/HOST connection. We do this more or less to prevent the use case you are detailing since you probably dont want your site exposed to those on your LAN in most cases.

To get around this i would guess you need to change the host-only adapter to either something else completely or change its settings to allow a wider range of IPs.
