### ISSUE TITLE
Feature Request: Do not use VirtualBox or Boot2Docker in Linux

### ISSUE THREAD

**Issue by eosrei** [kalabox/kalabox#720]
Adding this as a feature request since I know it's more work.

*In case someone seeing this doesn't know the reasoning: Linux supports LXC/Docker containers natively, so it's lots of overhead to run a virtual machine*

**Comment by pirog** [comment]
@eosrei i feel you on this but its unlikely we will do this at least as part of the default set up. The overhead sucks but the isolation is pretty key to making sure we can set things up correctly. 

At some point we could probably roll a "native" backend that the more savvy people could use instead of the b2d/machine backend.

**Comment by eosrei** [comment]
@pirog Yep, understandable. I don't expect it to be the standard method or implemented any time soon. More of a wishlist item, since I already have Docker and family on my machine.

**Comment by pirog** [comment]
i would **DEFINITELY** be very interested in supporting this at some point though!

**Comment by pirog** [comment]
Now that we have docker compose/machine in the mix for v0.11.0 the roadmap for this becomes a lot easier.

**Comment by eosrei** [comment]
Does this mean it's implemented?

**Comment by pirog** [comment]
Not yet but here is what we would need to do to get this to work

### Have some sort of "native" mode detection/indicator/option

We need a way to specify an install in "native" mode. If the detected platform is linux and the DISPLAY env is set we can automatically assume native mode. (might be a better way to detect whether linux is "server" or "desktop"). We also should allow native mode to be set with something like KALABOX_NATIVE=true for users who want to install in native mode while on desktop.

### Have the docker engine installed directly on the host instead of on a VM

There are two ways to do this 

1. directly installing docker-engine
2. using a docker-machine generic driver 

I think i am leaning towards the docker-machine option since it would require the least amount of code and we would be advantaged by all the machine power. Here are what each would take

#### Docker machine

1. In plugins/kalabox-engine-docker/lib/provider/machine.js we would need to have generic driver options to install a local docker machine if "native" mode is on. 
2. We need to make sure our engine config and other relevant functions are set correctly when we are in native mode. biggest one here would be the engine config. 
3. We need to make sure that virtualbox (also syncthing? other things?) is not downloaded and installed when in native mode

#### Docker engine

1. We would need to also do no. 3 above but additionally make sure we grab and install the docker-engine. 
2. We would want to have probably a completely separate provider module for the engine that would get loaded instead of machine.js

For either we might want to create an abstract provider interface that either "virtualbox" or "generic/engine" drivers can implement.

**Comment by pirog** [comment]
WHoops closed by mistake

**Comment by eosrei** [comment]
:smile: Haha that's actually what prompted my comment above.

**Comment by pirog** [comment]
Yeah word. Makes WAY more sense now.

**Comment by pirog** [comment]
@eosrei this is happening!

**Comment by eosrei** [comment]
@pirog Awesome!

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox/tree/720-nativeLinux is coming along but we still need to resolve a few things

- [ ] handle "sharing" without syncthing 
- [ ] fix permission handling via #994 and #1092
