### ISSUE TITLE
Can someone explain how to use composer and/or composer manager module with kbox2?

### ISSUE THREAD

**Issue by escapesequence** [kalabox/kalabox#820]
Thanks in advance.

**Comment by reynoldsalec** [comment]
I would suggest installing Composer and using it within your Kalabox app's code directory as you normally would with another Drupal project that utilizes Composer. There isn't really a need to install Composer in the virtualized environment; that's the nice part about Kalabox, that you can use native tools like Composer on your computer that you're used to.

I haven't used Composer Manager, but if it simply collects all the composer files from your modules into a single composer.json file, then the same approach should work.

Hope that helps!

**Comment by reynoldsalec** [comment]
@pirog might have something else to say here if he thinks including Composer could have additional benefits, but I'm going to close this out for right now unless you have further questions/comments @escapesequence.

**Comment by WidgetsBurritos** [comment]
I know @escapesequence asked this question back in January, and this thread has been closed for a while, but in case he still needs it or anyone else gets here from a Google search (which is how I originally found this thread), this is how I did it on D7.

The problem here is that the default settings of Composer Manager install the `composer.json` file in `sites/default/files/composer/` directory not in the docroot by default. Additionally, while [Composer Manager recommends using ../ and ../vendor as the paths for things](https://www.drupal.org/node/2405805) this doesn't really work with Kalabox (and presumably Pantheon), since that would exist outside of the necessary container. You can obviously relocate all the files elsewhere, but it's really not necessary as long as you're okay with running composer inside your `APPROOT/files/composer` folder.

So here's the step by step way to get it running:

1. Install "Composer Manager" module. 

2. Go into the admin panel for `http://whatever.kbox/admin/config/system/composer-manager`

3. Click *Rebuild composer.json* button

4. From a terminal window navigate to the directory containing the `composer.json` file and then install composer from there:

  ```
cd APPROOT/files/composer
composer install
```

5. Success!
