### ISSUE TITLE
Feature Request:  Let me choose whether to download my files via backup or rsync

### ISSUE THREAD

**Issue by rvtraveller** [kalabox/kalabox#851]
Overview:

The `pullFiles()` function in pull.js (https://github.com/kalabox/kalabox-app-pantheon/blob/v0.10/app/plugins/kalabox-plugin-pantheon/lib/pull.js#L268) selectively determines whether or not to download files via Pantheon backup or rsync based on whether this is the initial clone of a site or not.  For most use cases, this is a great way to do it.  However, this is problematic for those sites with large files directories.

Example use case:

I have a site on Pantheon with ~40GB of files in the compressed backup (FWIW, they are largely PDFs and images).  Prior to this content being loaded into the site on Pantheon, I had cloned this site to my local machine using Kalabox.  This process worked great and continues to run great when I pull.  When I try and clone the site on a new machine (such as a new computer at work for a new team member), the initial creation takes forever and eventually errors out because Kalabox is trying to download a 40GB archive file and then decompress it.  Ultimately, this process ends up failing and leaves the local copy of the site in an unusable state (because other post-file-pull tasks haven't run).

Suggested resolution:

I see 2 different ways to resolve this.  Option 1 would be to provide a way for the user to specify that they want to download files via rsync instead of compressed archive.  This could either be a command line flag passed into the create command (seems a little wonky) or a prompt to the user when it gets to the clone step.  Option 2 (and I'm not sure if this is feasible) is to intelligently check the size of the backup in Pantheon before downloading it and if it is over a certain threshold, revert to rsync.  This option does have the negative drawback that if a backup doesn't exist and Kalabox has to make one, then the user is again stuck waiting for a long time because creating a 40GB archive of files can take hours (or more).

**Comment by bthompson-mindgrub** [comment]
Per request, moving this from kalabox/kalabox-app-pantheon#73.

On that issue, @pirog said:

>So i think we can do both option 1 and option 2 here. that said i think the best thing you can do for large file directories is to use the drupal file proxy module. It is also worth noting that sometimes its faster to create a backup and download it vs rsyncing.

**Comment by pirog** [comment]
@bthompson-mindgrub! 

we are focusing on getting the GUI out in the next few weeks but def will loop back around to this soon thereafter!

**Comment by pirog** [comment]
@rvtraveller im thinking to do an option 1 for the CLI for the 12-alpha3 sprint. 

Because this seems like more an edge case i was going to add it as a flag but not part of the interactive questions when you do a pull or create. Maybe something like `--pull-files-by=rsync|archive`

How does that sound?

**Comment by rvtraveller** [comment]
+1 to having it be just a cli flag.  I agree that it is a bit of an edge case (just one that I happened to hit).

**Comment by pirog** [comment]
@rvtraveller so we are introducing two news flags that, while not exactly like this, might be close enough to warrant not adding this. See https://github.com/kalabox/kalabox/issues/1154

In this scenario you'd be able to do an intial create without pulling files. Then a subsequent `kbox pull` would pull your files with `rsync`. It's a little workaroundy but it might be better to just document this instead of adding another potentially confusing flag. 

What do you think?

**Comment by rvtraveller** [comment]
@pirog sounds like a reasonable compromise :+1:.
