### ISSUE TITLE
Add SSL back to pantheon appserver container

### ISSUE THREAD

**Issue by spazzwig** [kalabox/kalabox#990]
Hello,

In both versions 0.11.1 and 0.11.2, with a freshly created app, http://site.kbox works fine but https://site.kbox is returning error 400 (Lost in the clouds page).

I've restarted, rebuilt, created fresh, pulled. I haven't yet looked closely at the configs, or directly at the VM/containers.

Anyone experience the same, or have any suggestions?

Thanks,
Gabe

**Comment by pirog** [comment]
@spazzwig the answer here is actually a little convoluted. 

we were handling https for pantheon on the edge container and not directly on the appserver. so if you go to https://edge.appname.kbox you should get your site over ssl.

originally we were setting appname.kbox to point to the edge instead of the directly to the appserver but this caused some trouble with development due to varnish caching so we switched appname.kbox to point directly to the appserver and added edge.appname.kbox for people who need varnish testing. 

we def should add SSL back into the appserver directly.

**Comment by spazzwig** [comment]
Thank you Mike, that clears things up and hitting edge directly works fine until the appserver is SSL enabled again. BTW love how much faster recent Kalabox versions have become!

**Comment by pirog** [comment]
@spazzwig this should be in the next release. here is the code change if you wanted to try and get it going manually
https://github.com/kalabox/kalabox-app-pantheon/commit/a6011dcdbe6b9a9fc9163b3ea12865228cc0a423
