### ISSUE TITLE
GUI - Kalabox can't/won't create ".../code/sites/default/files" ... or maybe its an issue with "/tmp"

### ISSUE THREAD

**Issue by alphex** [kalabox/kalabox#994]
Using GUI.
Created new site on Pantheon.
Only ran "install" script on pantheon.  No configuration changed made on GUI in Pantheon.

Used Kalabox GUI to pull down site.
Started to configure things.
Was able to DRUSH DL modules and themes to directories as I needed/wanted.

Went to http://sitename.kbox/admin/config/development/performance to turn off caching.

Presented with error message : 
"Set up the public files directory to make these optimizations available."

Went to file system screen "/admin/config/media/file-system"

All directories are correct, no errors.
Clicked save button.
No errors.

Went to terminal, on localhost (not in the container)
.../sites/default/files was not created.

mkdir files
sudo chmod -R 777 files

Went back to caching page, cleared caches, saved config, same error about needing to set up public files directory.

Went to file system screen, still showing no errors.

As normal, its looking to use "/tmp".   But I have no way of confirming /tmp works since I don't have shell access to container?

http://z.alphex.io/2016-02-11_10-41-19.jpg

Suspecting /tmp isn't accessible in the file system?

**Comment by pirog** [comment]
Hey @alphex so a couple of things to point out here. 

1. Your files are actually available one directory up from your code in `files`. 
2. There is a `kbox terminal` command you can run inside your app that will drop you into a shell in your appserver container.

**Comment by labboy0276** [comment]
Not sure if this helps this convo any.  While doing a kbox drush up on a system with advagg on it, I get messages like this:

```
WD advagg: Reading from the file system failed.                      [error]
sites/all/modules/contrib/jquery_update/replace/misc/jquery.form.min.js

WD advagg: Reading from the file system failed.                      [error]
sites/all/modules/contrib/jquery_update/replace/misc/1.9/jquery.ba-bbq.min.js

WD advagg: Reading from the file system failed.                      [error]
sites/all/modules/contrib/field_group/field_group.css 
Performed update: field_group_update_7008                            [ok]
Performed update: file_entity_update_7216                            [ok]
WD advagg: Reading from the file system failed.                      [error]
sites/all/modules/panopoly_theme/plugins/layouts/moscone_flipped/moscone-flipped.css

WD advagg: Reading from the file system failed.                      [error]
public://ctools/css/ad57ff1546b4e3e493a0d16eb09e3ad9_28.css 
WD advagg: Reading from the file system failed.                      [error]
sites/all/modules/contrib/panopoly_theme/plugins/layouts/sutro/sutro.css

WD advagg: Reading from the file system failed.                      [error]
```

Notice it can't read the public:// file system and it seems like the code directory from the command line

**Comment by pirog** [comment]
Very helpful. I added this issue into the current sprint and we'll see if there is something we can do on the kalabox side to get this to work as expected.

**Comment by pirog** [comment]
Ok. So as far as i can tell the reason why this is happening is because on kalabox `sites/default/files` is actually a symlink to `/media` and various things are doing a check like this

```php
  $directory = 'public://';
  $is_writable = is_dir($directory) && is_writable($directory);
  $disabled = !$is_writable;
```

As you might imagine `is_dir` returns false. Going to explore how to get this to work nice with symlinks.

**Comment by alphex** [comment]
I swear I posted this comment earlier.

I SYMLINKED  appname/code/sites/default files to point at appname/files

and then chmod 777 appname/files.

This solved the problem.

**Comment by pirog** [comment]
@alphex yes i saw that. 

what is weird about what you posted is that doing that on your host machine shouldn't matter since anything at sites/default/files is not shared into the appserver container by default. we also cant handle this on the host side since symlinking on windows is a PITA and requires elevated permissions. 

even more weird is that we set this up by default on the container side so that s/d/f points to /media which is where your files actually are. guessing you are on teh right track but just need to get it set up on the container side.

**Comment by pirog** [comment]
ok so the part of @alphex's solution that gets this to actually work is the chmod 777 of the files directory since these permissions also get shared into the container making /media writable. 

That said we still dont have a complete solution until we can get the webserver to be able to write to /media without having to change peoples permissions around.

**Comment by pirog** [comment]
So i've tracked this down a little bit more. It looks like if you wrap things in `drupal_realpath` the checks return correctly. So something must be funky in resolving `public://` straight up

```
  $directory = drupal_realpath('public://');
  $is_writable = is_dir($directory) && is_writable($directory);
```

**Comment by labboy0276** [comment]
Hello!

So I ran chmod -Rv 777 files in my app root and ran my original commandz for drush up.  This resolves said public:// file issue, but I still have one issue below:

```
WD advagg: Reading from the file system failed.                      [error]
profiles/panopoly/modules/contrib/views/js/exposed-form-ajax.js 
```

**Comment by pirog** [comment]
Ok so did a little more tracking on this. It looks like the key factors are 

1. We share our host `appname/files` into the container at `/media`, `/media` is getting our host uid/group which shows up as `1000 staff` in the container for an OSX user. 
2. `is_writable('public://')` returns `false` but `is_writable(drupal_realpath('public://'))` return `true`

the workaround posted by @alphex (without the symlink part) and @labboy0276 seems to work for now but obviously chmod 777 is not always the best way to go. since we are local this shouldnt be a huge deal for now.

**Comment by pirog** [comment]
Looks like this has been a known drupal issue for quite some time
https://www.drupal.org/node/1899126
https://www.drupal.org/node/944582 

and others

I'm going to backlog this issue for now. people should use the workaround until we have this resolved upstream.

**Comment by pirog** [comment]
We should look at what we are doing in the generic drupal app to resolve this. Specifically making sure we map our B2D perms over to the user running the webserver

```bash
# Do this so our mounted VB volumes work
echo "Remapping apache permissions for VB sharing compat..."
usermod -u 1000 www-data
usermod -G staff www-data
chown -Rf www-data:www-data /var/www/html
```
